-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rgb2gray_top is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_IN_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_IN_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_IN_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_IN_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_IN_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_IN_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_IN_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_IN_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_OUT_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_OUT_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_OUT_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_OUT_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_OUT_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_OUT_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_OUT_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_OUT_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_IN_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_IN_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_IN_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_GMEM_OUT_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_OUT_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_OUT_CACHE_VALUE : INTEGER := 3 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_gmem_in_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_in_AWREADY : IN STD_LOGIC;
    m_axi_gmem_in_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_in_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_ID_WIDTH-1 downto 0);
    m_axi_gmem_in_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_in_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_in_WVALID : OUT STD_LOGIC;
    m_axi_gmem_in_WREADY : IN STD_LOGIC;
    m_axi_gmem_in_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_DATA_WIDTH-1 downto 0);
    m_axi_gmem_in_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_in_WLAST : OUT STD_LOGIC;
    m_axi_gmem_in_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_ID_WIDTH-1 downto 0);
    m_axi_gmem_in_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_in_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_in_ARREADY : IN STD_LOGIC;
    m_axi_gmem_in_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_in_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_ID_WIDTH-1 downto 0);
    m_axi_gmem_in_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_in_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_in_RVALID : IN STD_LOGIC;
    m_axi_gmem_in_RREADY : OUT STD_LOGIC;
    m_axi_gmem_in_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_DATA_WIDTH-1 downto 0);
    m_axi_gmem_in_RLAST : IN STD_LOGIC;
    m_axi_gmem_in_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_ID_WIDTH-1 downto 0);
    m_axi_gmem_in_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_in_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_BVALID : IN STD_LOGIC;
    m_axi_gmem_in_BREADY : OUT STD_LOGIC;
    m_axi_gmem_in_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_ID_WIDTH-1 downto 0);
    m_axi_gmem_in_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_IN_BUSER_WIDTH-1 downto 0);
    m_axi_gmem_out_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_out_AWREADY : IN STD_LOGIC;
    m_axi_gmem_out_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_out_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_ID_WIDTH-1 downto 0);
    m_axi_gmem_out_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_out_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_out_WVALID : OUT STD_LOGIC;
    m_axi_gmem_out_WREADY : IN STD_LOGIC;
    m_axi_gmem_out_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_DATA_WIDTH-1 downto 0);
    m_axi_gmem_out_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_out_WLAST : OUT STD_LOGIC;
    m_axi_gmem_out_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_ID_WIDTH-1 downto 0);
    m_axi_gmem_out_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_out_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_out_ARREADY : IN STD_LOGIC;
    m_axi_gmem_out_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_out_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_ID_WIDTH-1 downto 0);
    m_axi_gmem_out_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_out_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_out_RVALID : IN STD_LOGIC;
    m_axi_gmem_out_RREADY : OUT STD_LOGIC;
    m_axi_gmem_out_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_DATA_WIDTH-1 downto 0);
    m_axi_gmem_out_RLAST : IN STD_LOGIC;
    m_axi_gmem_out_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_ID_WIDTH-1 downto 0);
    m_axi_gmem_out_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_out_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_BVALID : IN STD_LOGIC;
    m_axi_gmem_out_BREADY : OUT STD_LOGIC;
    m_axi_gmem_out_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_ID_WIDTH-1 downto 0);
    m_axi_gmem_out_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_OUT_BUSER_WIDTH-1 downto 0) );
end;


architecture behav of rgb2gray_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "rgb2gray_top_rgb2gray_top,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.920000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=5377,HLS_SYN_LUT=6500,HLS_VERSION=2024_1}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal m_axi_in : STD_LOGIC_VECTOR (63 downto 0);
    signal m_axi_out : STD_LOGIC_VECTOR (63 downto 0);
    signal addr_in : STD_LOGIC_VECTOR (31 downto 0);
    signal addr_out : STD_LOGIC_VECTOR (31 downto 0);
    signal num_pixels : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal gmem_in_AWREADY : STD_LOGIC;
    signal gmem_in_WREADY : STD_LOGIC;
    signal gmem_in_ARREADY : STD_LOGIC;
    signal gmem_in_RVALID : STD_LOGIC;
    signal gmem_in_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_in_RLAST : STD_LOGIC;
    signal gmem_in_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_in_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_in_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_in_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_in_BVALID : STD_LOGIC;
    signal gmem_out_AWREADY : STD_LOGIC;
    signal gmem_out_WREADY : STD_LOGIC;
    signal gmem_out_ARREADY : STD_LOGIC;
    signal gmem_out_RVALID : STD_LOGIC;
    signal gmem_out_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_out_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_out_BVALID : STD_LOGIC;
    signal gmem_out_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_out_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_out_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_m_axi_out_c_din : STD_LOGIC_VECTOR (63 downto 0);
    signal entry_proc_U0_m_axi_out_c_write : STD_LOGIC;
    signal entry_proc_U0_addr_out_c_din : STD_LOGIC_VECTOR (31 downto 0);
    signal entry_proc_U0_addr_out_c_write : STD_LOGIC;
    signal load_rgb_U0_ap_start : STD_LOGIC;
    signal load_rgb_U0_ap_done : STD_LOGIC;
    signal load_rgb_U0_ap_continue : STD_LOGIC;
    signal load_rgb_U0_ap_idle : STD_LOGIC;
    signal load_rgb_U0_ap_ready : STD_LOGIC;
    signal load_rgb_U0_m_axi_gmem_in_AWVALID : STD_LOGIC;
    signal load_rgb_U0_m_axi_gmem_in_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_WVALID : STD_LOGIC;
    signal load_rgb_U0_m_axi_gmem_in_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_WLAST : STD_LOGIC;
    signal load_rgb_U0_m_axi_gmem_in_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_ARVALID : STD_LOGIC;
    signal load_rgb_U0_m_axi_gmem_in_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load_rgb_U0_m_axi_gmem_in_RREADY : STD_LOGIC;
    signal load_rgb_U0_m_axi_gmem_in_BREADY : STD_LOGIC;
    signal load_rgb_U0_stream_rgb_din : STD_LOGIC_VECTOR (23 downto 0);
    signal load_rgb_U0_stream_rgb_write : STD_LOGIC;
    signal load_rgb_U0_start_out : STD_LOGIC;
    signal load_rgb_U0_start_write : STD_LOGIC;
    signal load_rgb_U0_num_pixels_c1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal load_rgb_U0_num_pixels_c1_write : STD_LOGIC;
    signal process_gray_U0_ap_start : STD_LOGIC;
    signal process_gray_U0_ap_done : STD_LOGIC;
    signal process_gray_U0_ap_continue : STD_LOGIC;
    signal process_gray_U0_ap_idle : STD_LOGIC;
    signal process_gray_U0_ap_ready : STD_LOGIC;
    signal process_gray_U0_stream_rgb_read : STD_LOGIC;
    signal process_gray_U0_stream_gray_din : STD_LOGIC_VECTOR (7 downto 0);
    signal process_gray_U0_stream_gray_write : STD_LOGIC;
    signal process_gray_U0_num_pixels_read : STD_LOGIC;
    signal process_gray_U0_num_pixels_c_din : STD_LOGIC_VECTOR (31 downto 0);
    signal process_gray_U0_num_pixels_c_write : STD_LOGIC;
    signal store_gray_U0_ap_start : STD_LOGIC;
    signal store_gray_U0_ap_done : STD_LOGIC;
    signal store_gray_U0_ap_continue : STD_LOGIC;
    signal store_gray_U0_ap_idle : STD_LOGIC;
    signal store_gray_U0_ap_ready : STD_LOGIC;
    signal store_gray_U0_num_pixels_read : STD_LOGIC;
    signal store_gray_U0_addr_out_read : STD_LOGIC;
    signal store_gray_U0_m_axi_out_read : STD_LOGIC;
    signal store_gray_U0_m_axi_gmem_out_AWVALID : STD_LOGIC;
    signal store_gray_U0_m_axi_gmem_out_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal store_gray_U0_m_axi_gmem_out_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal store_gray_U0_m_axi_gmem_out_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal store_gray_U0_m_axi_gmem_out_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal store_gray_U0_m_axi_gmem_out_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal store_gray_U0_m_axi_gmem_out_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal store_gray_U0_m_axi_gmem_out_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal store_gray_U0_m_axi_gmem_out_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal store_gray_U0_m_axi_gmem_out_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal store_gray_U0_m_axi_gmem_out_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal store_gray_U0_m_axi_gmem_out_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal store_gray_U0_m_axi_gmem_out_WVALID : STD_LOGIC;
    signal store_gray_U0_m_axi_gmem_out_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal store_gray_U0_m_axi_gmem_out_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal store_gray_U0_m_axi_gmem_out_WLAST : STD_LOGIC;
    signal store_gray_U0_m_axi_gmem_out_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal store_gray_U0_m_axi_gmem_out_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal store_gray_U0_m_axi_gmem_out_ARVALID : STD_LOGIC;
    signal store_gray_U0_m_axi_gmem_out_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal store_gray_U0_m_axi_gmem_out_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal store_gray_U0_m_axi_gmem_out_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal store_gray_U0_m_axi_gmem_out_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal store_gray_U0_m_axi_gmem_out_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal store_gray_U0_m_axi_gmem_out_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal store_gray_U0_m_axi_gmem_out_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal store_gray_U0_m_axi_gmem_out_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal store_gray_U0_m_axi_gmem_out_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal store_gray_U0_m_axi_gmem_out_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal store_gray_U0_m_axi_gmem_out_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal store_gray_U0_m_axi_gmem_out_RREADY : STD_LOGIC;
    signal store_gray_U0_m_axi_gmem_out_BREADY : STD_LOGIC;
    signal store_gray_U0_stream_gray_read : STD_LOGIC;
    signal m_axi_out_c_full_n : STD_LOGIC;
    signal m_axi_out_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal m_axi_out_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal m_axi_out_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal m_axi_out_c_empty_n : STD_LOGIC;
    signal addr_out_c_full_n : STD_LOGIC;
    signal addr_out_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal addr_out_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal addr_out_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal addr_out_c_empty_n : STD_LOGIC;
    signal stream_rgb_full_n : STD_LOGIC;
    signal stream_rgb_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal stream_rgb_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_rgb_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_rgb_empty_n : STD_LOGIC;
    signal num_pixels_c1_full_n : STD_LOGIC;
    signal num_pixels_c1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal num_pixels_c1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c1_empty_n : STD_LOGIC;
    signal stream_gray_full_n : STD_LOGIC;
    signal stream_gray_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal stream_gray_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_gray_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_gray_empty_n : STD_LOGIC;
    signal num_pixels_c_full_n : STD_LOGIC;
    signal num_pixels_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal num_pixels_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_load_rgb_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_load_rgb_U0_ap_ready : STD_LOGIC;
    signal start_for_store_gray_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_store_gray_U0_full_n : STD_LOGIC;
    signal start_for_store_gray_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_store_gray_U0_empty_n : STD_LOGIC;
    signal start_for_process_gray_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_process_gray_U0_full_n : STD_LOGIC;
    signal start_for_process_gray_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_process_gray_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component rgb2gray_top_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_out : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_c_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_c_full_n : IN STD_LOGIC;
        m_axi_out_c_write : OUT STD_LOGIC;
        addr_out : IN STD_LOGIC_VECTOR (31 downto 0);
        addr_out_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        addr_out_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        addr_out_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        addr_out_c_full_n : IN STD_LOGIC;
        addr_out_c_write : OUT STD_LOGIC );
    end component;


    component rgb2gray_top_load_rgb IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_in_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_in_AWREADY : IN STD_LOGIC;
        m_axi_gmem_in_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_in_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_in_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_WVALID : OUT STD_LOGIC;
        m_axi_gmem_in_WREADY : IN STD_LOGIC;
        m_axi_gmem_in_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_in_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_WLAST : OUT STD_LOGIC;
        m_axi_gmem_in_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_in_ARREADY : IN STD_LOGIC;
        m_axi_gmem_in_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_in_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_in_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_RVALID : IN STD_LOGIC;
        m_axi_gmem_in_RREADY : OUT STD_LOGIC;
        m_axi_gmem_in_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_in_RLAST : IN STD_LOGIC;
        m_axi_gmem_in_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_in_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_BVALID : IN STD_LOGIC;
        m_axi_gmem_in_BREADY : OUT STD_LOGIC;
        m_axi_gmem_in_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_rgb_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_rgb_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_rgb_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_rgb_full_n : IN STD_LOGIC;
        stream_rgb_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_in : IN STD_LOGIC_VECTOR (63 downto 0);
        addr_in : IN STD_LOGIC_VECTOR (31 downto 0);
        num_pixels : IN STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_c1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_c1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c1_full_n : IN STD_LOGIC;
        num_pixels_c1_write : OUT STD_LOGIC );
    end component;


    component rgb2gray_top_process_gray IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_rgb_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        stream_rgb_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_rgb_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_rgb_empty_n : IN STD_LOGIC;
        stream_rgb_read : OUT STD_LOGIC;
        stream_gray_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        stream_gray_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_gray_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_gray_full_n : IN STD_LOGIC;
        stream_gray_write : OUT STD_LOGIC;
        num_pixels_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_empty_n : IN STD_LOGIC;
        num_pixels_read : OUT STD_LOGIC;
        num_pixels_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c_full_n : IN STD_LOGIC;
        num_pixels_c_write : OUT STD_LOGIC );
    end component;


    component rgb2gray_top_store_gray IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        num_pixels_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_empty_n : IN STD_LOGIC;
        num_pixels_read : OUT STD_LOGIC;
        addr_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        addr_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        addr_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        addr_out_empty_n : IN STD_LOGIC;
        addr_out_read : OUT STD_LOGIC;
        m_axi_out_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_empty_n : IN STD_LOGIC;
        m_axi_out_read : OUT STD_LOGIC;
        m_axi_gmem_out_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_out_AWREADY : IN STD_LOGIC;
        m_axi_gmem_out_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_out_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_out_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_out_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_out_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_WVALID : OUT STD_LOGIC;
        m_axi_gmem_out_WREADY : IN STD_LOGIC;
        m_axi_gmem_out_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_out_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_WLAST : OUT STD_LOGIC;
        m_axi_gmem_out_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_out_ARREADY : IN STD_LOGIC;
        m_axi_gmem_out_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_out_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_out_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_out_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_out_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_RVALID : IN STD_LOGIC;
        m_axi_gmem_out_RREADY : OUT STD_LOGIC;
        m_axi_gmem_out_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_out_RLAST : IN STD_LOGIC;
        m_axi_gmem_out_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_out_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_BVALID : IN STD_LOGIC;
        m_axi_gmem_out_BREADY : OUT STD_LOGIC;
        m_axi_gmem_out_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_gray_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        stream_gray_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_gray_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_gray_empty_n : IN STD_LOGIC;
        stream_gray_read : OUT STD_LOGIC );
    end component;


    component rgb2gray_top_fifo_w64_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rgb2gray_top_fifo_w32_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rgb2gray_top_fifo_w24_d16_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (23 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (23 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rgb2gray_top_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rgb2gray_top_fifo_w8_d16_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rgb2gray_top_start_for_store_gray_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rgb2gray_top_start_for_process_gray_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rgb2gray_top_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        m_axi_in : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        addr_in : OUT STD_LOGIC_VECTOR (31 downto 0);
        addr_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        num_pixels : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_continue : OUT STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component rgb2gray_top_gmem_in_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component rgb2gray_top_gmem_out_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component rgb2gray_top_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        m_axi_in => m_axi_in,
        m_axi_out => m_axi_out,
        addr_in => addr_in,
        addr_out => addr_out,
        num_pixels => num_pixels,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_continue => ap_continue,
        ap_idle => ap_idle);

    gmem_in_m_axi_U : component rgb2gray_top_gmem_in_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 73,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_IN_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_IN_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_IN_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_IN_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_IN_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_IN_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_IN_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_IN_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_IN_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_IN_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_IN_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_gmem_in_AWVALID,
        AWREADY => m_axi_gmem_in_AWREADY,
        AWADDR => m_axi_gmem_in_AWADDR,
        AWID => m_axi_gmem_in_AWID,
        AWLEN => m_axi_gmem_in_AWLEN,
        AWSIZE => m_axi_gmem_in_AWSIZE,
        AWBURST => m_axi_gmem_in_AWBURST,
        AWLOCK => m_axi_gmem_in_AWLOCK,
        AWCACHE => m_axi_gmem_in_AWCACHE,
        AWPROT => m_axi_gmem_in_AWPROT,
        AWQOS => m_axi_gmem_in_AWQOS,
        AWREGION => m_axi_gmem_in_AWREGION,
        AWUSER => m_axi_gmem_in_AWUSER,
        WVALID => m_axi_gmem_in_WVALID,
        WREADY => m_axi_gmem_in_WREADY,
        WDATA => m_axi_gmem_in_WDATA,
        WSTRB => m_axi_gmem_in_WSTRB,
        WLAST => m_axi_gmem_in_WLAST,
        WID => m_axi_gmem_in_WID,
        WUSER => m_axi_gmem_in_WUSER,
        ARVALID => m_axi_gmem_in_ARVALID,
        ARREADY => m_axi_gmem_in_ARREADY,
        ARADDR => m_axi_gmem_in_ARADDR,
        ARID => m_axi_gmem_in_ARID,
        ARLEN => m_axi_gmem_in_ARLEN,
        ARSIZE => m_axi_gmem_in_ARSIZE,
        ARBURST => m_axi_gmem_in_ARBURST,
        ARLOCK => m_axi_gmem_in_ARLOCK,
        ARCACHE => m_axi_gmem_in_ARCACHE,
        ARPROT => m_axi_gmem_in_ARPROT,
        ARQOS => m_axi_gmem_in_ARQOS,
        ARREGION => m_axi_gmem_in_ARREGION,
        ARUSER => m_axi_gmem_in_ARUSER,
        RVALID => m_axi_gmem_in_RVALID,
        RREADY => m_axi_gmem_in_RREADY,
        RDATA => m_axi_gmem_in_RDATA,
        RLAST => m_axi_gmem_in_RLAST,
        RID => m_axi_gmem_in_RID,
        RUSER => m_axi_gmem_in_RUSER,
        RRESP => m_axi_gmem_in_RRESP,
        BVALID => m_axi_gmem_in_BVALID,
        BREADY => m_axi_gmem_in_BREADY,
        BRESP => m_axi_gmem_in_BRESP,
        BID => m_axi_gmem_in_BID,
        BUSER => m_axi_gmem_in_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => load_rgb_U0_m_axi_gmem_in_ARVALID,
        I_CH0_ARREADY => gmem_in_ARREADY,
        I_CH0_ARADDR => load_rgb_U0_m_axi_gmem_in_ARADDR,
        I_CH0_ARLEN => load_rgb_U0_m_axi_gmem_in_ARLEN,
        I_CH0_RVALID => gmem_in_RVALID,
        I_CH0_RREADY => load_rgb_U0_m_axi_gmem_in_RREADY,
        I_CH0_RDATA => gmem_in_RDATA,
        I_CH0_RFIFONUM => gmem_in_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => gmem_in_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => gmem_in_WREADY,
        I_CH0_WDATA => ap_const_lv32_0,
        I_CH0_WSTRB => ap_const_lv4_0,
        I_CH0_BVALID => gmem_in_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    gmem_out_m_axi_U : component rgb2gray_top_gmem_out_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 73,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_OUT_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_OUT_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_OUT_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_OUT_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_OUT_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_OUT_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_OUT_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_OUT_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_OUT_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_OUT_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_OUT_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 0,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem_out_AWVALID,
        AWREADY => m_axi_gmem_out_AWREADY,
        AWADDR => m_axi_gmem_out_AWADDR,
        AWID => m_axi_gmem_out_AWID,
        AWLEN => m_axi_gmem_out_AWLEN,
        AWSIZE => m_axi_gmem_out_AWSIZE,
        AWBURST => m_axi_gmem_out_AWBURST,
        AWLOCK => m_axi_gmem_out_AWLOCK,
        AWCACHE => m_axi_gmem_out_AWCACHE,
        AWPROT => m_axi_gmem_out_AWPROT,
        AWQOS => m_axi_gmem_out_AWQOS,
        AWREGION => m_axi_gmem_out_AWREGION,
        AWUSER => m_axi_gmem_out_AWUSER,
        WVALID => m_axi_gmem_out_WVALID,
        WREADY => m_axi_gmem_out_WREADY,
        WDATA => m_axi_gmem_out_WDATA,
        WSTRB => m_axi_gmem_out_WSTRB,
        WLAST => m_axi_gmem_out_WLAST,
        WID => m_axi_gmem_out_WID,
        WUSER => m_axi_gmem_out_WUSER,
        ARVALID => m_axi_gmem_out_ARVALID,
        ARREADY => m_axi_gmem_out_ARREADY,
        ARADDR => m_axi_gmem_out_ARADDR,
        ARID => m_axi_gmem_out_ARID,
        ARLEN => m_axi_gmem_out_ARLEN,
        ARSIZE => m_axi_gmem_out_ARSIZE,
        ARBURST => m_axi_gmem_out_ARBURST,
        ARLOCK => m_axi_gmem_out_ARLOCK,
        ARCACHE => m_axi_gmem_out_ARCACHE,
        ARPROT => m_axi_gmem_out_ARPROT,
        ARQOS => m_axi_gmem_out_ARQOS,
        ARREGION => m_axi_gmem_out_ARREGION,
        ARUSER => m_axi_gmem_out_ARUSER,
        RVALID => m_axi_gmem_out_RVALID,
        RREADY => m_axi_gmem_out_RREADY,
        RDATA => m_axi_gmem_out_RDATA,
        RLAST => m_axi_gmem_out_RLAST,
        RID => m_axi_gmem_out_RID,
        RUSER => m_axi_gmem_out_RUSER,
        RRESP => m_axi_gmem_out_RRESP,
        BVALID => m_axi_gmem_out_BVALID,
        BREADY => m_axi_gmem_out_BREADY,
        BRESP => m_axi_gmem_out_BRESP,
        BID => m_axi_gmem_out_BID,
        BUSER => m_axi_gmem_out_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => ap_const_logic_0,
        I_CH0_ARREADY => gmem_out_ARREADY,
        I_CH0_ARADDR => ap_const_lv64_0,
        I_CH0_ARLEN => ap_const_lv32_0,
        I_CH0_RVALID => gmem_out_RVALID,
        I_CH0_RREADY => ap_const_logic_0,
        I_CH0_RDATA => gmem_out_RDATA,
        I_CH0_RFIFONUM => gmem_out_RFIFONUM,
        I_CH0_AWVALID => store_gray_U0_m_axi_gmem_out_AWVALID,
        I_CH0_AWREADY => gmem_out_AWREADY,
        I_CH0_AWADDR => store_gray_U0_m_axi_gmem_out_AWADDR,
        I_CH0_AWLEN => store_gray_U0_m_axi_gmem_out_AWLEN,
        I_CH0_WVALID => store_gray_U0_m_axi_gmem_out_WVALID,
        I_CH0_WREADY => gmem_out_WREADY,
        I_CH0_WDATA => store_gray_U0_m_axi_gmem_out_WDATA,
        I_CH0_WSTRB => store_gray_U0_m_axi_gmem_out_WSTRB,
        I_CH0_BVALID => gmem_out_BVALID,
        I_CH0_BREADY => store_gray_U0_m_axi_gmem_out_BREADY);

    entry_proc_U0 : component rgb2gray_top_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => start_for_store_gray_U0_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        m_axi_out => m_axi_out,
        m_axi_out_c_din => entry_proc_U0_m_axi_out_c_din,
        m_axi_out_c_num_data_valid => m_axi_out_c_num_data_valid,
        m_axi_out_c_fifo_cap => m_axi_out_c_fifo_cap,
        m_axi_out_c_full_n => m_axi_out_c_full_n,
        m_axi_out_c_write => entry_proc_U0_m_axi_out_c_write,
        addr_out => addr_out,
        addr_out_c_din => entry_proc_U0_addr_out_c_din,
        addr_out_c_num_data_valid => addr_out_c_num_data_valid,
        addr_out_c_fifo_cap => addr_out_c_fifo_cap,
        addr_out_c_full_n => addr_out_c_full_n,
        addr_out_c_write => entry_proc_U0_addr_out_c_write);

    load_rgb_U0 : component rgb2gray_top_load_rgb
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => load_rgb_U0_ap_start,
        start_full_n => start_for_process_gray_U0_full_n,
        ap_done => load_rgb_U0_ap_done,
        ap_continue => load_rgb_U0_ap_continue,
        ap_idle => load_rgb_U0_ap_idle,
        ap_ready => load_rgb_U0_ap_ready,
        m_axi_gmem_in_AWVALID => load_rgb_U0_m_axi_gmem_in_AWVALID,
        m_axi_gmem_in_AWREADY => ap_const_logic_0,
        m_axi_gmem_in_AWADDR => load_rgb_U0_m_axi_gmem_in_AWADDR,
        m_axi_gmem_in_AWID => load_rgb_U0_m_axi_gmem_in_AWID,
        m_axi_gmem_in_AWLEN => load_rgb_U0_m_axi_gmem_in_AWLEN,
        m_axi_gmem_in_AWSIZE => load_rgb_U0_m_axi_gmem_in_AWSIZE,
        m_axi_gmem_in_AWBURST => load_rgb_U0_m_axi_gmem_in_AWBURST,
        m_axi_gmem_in_AWLOCK => load_rgb_U0_m_axi_gmem_in_AWLOCK,
        m_axi_gmem_in_AWCACHE => load_rgb_U0_m_axi_gmem_in_AWCACHE,
        m_axi_gmem_in_AWPROT => load_rgb_U0_m_axi_gmem_in_AWPROT,
        m_axi_gmem_in_AWQOS => load_rgb_U0_m_axi_gmem_in_AWQOS,
        m_axi_gmem_in_AWREGION => load_rgb_U0_m_axi_gmem_in_AWREGION,
        m_axi_gmem_in_AWUSER => load_rgb_U0_m_axi_gmem_in_AWUSER,
        m_axi_gmem_in_WVALID => load_rgb_U0_m_axi_gmem_in_WVALID,
        m_axi_gmem_in_WREADY => ap_const_logic_0,
        m_axi_gmem_in_WDATA => load_rgb_U0_m_axi_gmem_in_WDATA,
        m_axi_gmem_in_WSTRB => load_rgb_U0_m_axi_gmem_in_WSTRB,
        m_axi_gmem_in_WLAST => load_rgb_U0_m_axi_gmem_in_WLAST,
        m_axi_gmem_in_WID => load_rgb_U0_m_axi_gmem_in_WID,
        m_axi_gmem_in_WUSER => load_rgb_U0_m_axi_gmem_in_WUSER,
        m_axi_gmem_in_ARVALID => load_rgb_U0_m_axi_gmem_in_ARVALID,
        m_axi_gmem_in_ARREADY => gmem_in_ARREADY,
        m_axi_gmem_in_ARADDR => load_rgb_U0_m_axi_gmem_in_ARADDR,
        m_axi_gmem_in_ARID => load_rgb_U0_m_axi_gmem_in_ARID,
        m_axi_gmem_in_ARLEN => load_rgb_U0_m_axi_gmem_in_ARLEN,
        m_axi_gmem_in_ARSIZE => load_rgb_U0_m_axi_gmem_in_ARSIZE,
        m_axi_gmem_in_ARBURST => load_rgb_U0_m_axi_gmem_in_ARBURST,
        m_axi_gmem_in_ARLOCK => load_rgb_U0_m_axi_gmem_in_ARLOCK,
        m_axi_gmem_in_ARCACHE => load_rgb_U0_m_axi_gmem_in_ARCACHE,
        m_axi_gmem_in_ARPROT => load_rgb_U0_m_axi_gmem_in_ARPROT,
        m_axi_gmem_in_ARQOS => load_rgb_U0_m_axi_gmem_in_ARQOS,
        m_axi_gmem_in_ARREGION => load_rgb_U0_m_axi_gmem_in_ARREGION,
        m_axi_gmem_in_ARUSER => load_rgb_U0_m_axi_gmem_in_ARUSER,
        m_axi_gmem_in_RVALID => gmem_in_RVALID,
        m_axi_gmem_in_RREADY => load_rgb_U0_m_axi_gmem_in_RREADY,
        m_axi_gmem_in_RDATA => gmem_in_RDATA,
        m_axi_gmem_in_RLAST => gmem_in_RLAST,
        m_axi_gmem_in_RID => gmem_in_RID,
        m_axi_gmem_in_RFIFONUM => gmem_in_RFIFONUM,
        m_axi_gmem_in_RUSER => gmem_in_RUSER,
        m_axi_gmem_in_RRESP => gmem_in_RRESP,
        m_axi_gmem_in_BVALID => ap_const_logic_0,
        m_axi_gmem_in_BREADY => load_rgb_U0_m_axi_gmem_in_BREADY,
        m_axi_gmem_in_BRESP => ap_const_lv2_0,
        m_axi_gmem_in_BID => ap_const_lv1_0,
        m_axi_gmem_in_BUSER => ap_const_lv1_0,
        stream_rgb_din => load_rgb_U0_stream_rgb_din,
        stream_rgb_num_data_valid => stream_rgb_num_data_valid,
        stream_rgb_fifo_cap => stream_rgb_fifo_cap,
        stream_rgb_full_n => stream_rgb_full_n,
        stream_rgb_write => load_rgb_U0_stream_rgb_write,
        start_out => load_rgb_U0_start_out,
        start_write => load_rgb_U0_start_write,
        m_axi_in => m_axi_in,
        addr_in => addr_in,
        num_pixels => num_pixels,
        num_pixels_c1_din => load_rgb_U0_num_pixels_c1_din,
        num_pixels_c1_num_data_valid => num_pixels_c1_num_data_valid,
        num_pixels_c1_fifo_cap => num_pixels_c1_fifo_cap,
        num_pixels_c1_full_n => num_pixels_c1_full_n,
        num_pixels_c1_write => load_rgb_U0_num_pixels_c1_write);

    process_gray_U0 : component rgb2gray_top_process_gray
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => process_gray_U0_ap_start,
        ap_done => process_gray_U0_ap_done,
        ap_continue => process_gray_U0_ap_continue,
        ap_idle => process_gray_U0_ap_idle,
        ap_ready => process_gray_U0_ap_ready,
        stream_rgb_dout => stream_rgb_dout,
        stream_rgb_num_data_valid => stream_rgb_num_data_valid,
        stream_rgb_fifo_cap => stream_rgb_fifo_cap,
        stream_rgb_empty_n => stream_rgb_empty_n,
        stream_rgb_read => process_gray_U0_stream_rgb_read,
        stream_gray_din => process_gray_U0_stream_gray_din,
        stream_gray_num_data_valid => stream_gray_num_data_valid,
        stream_gray_fifo_cap => stream_gray_fifo_cap,
        stream_gray_full_n => stream_gray_full_n,
        stream_gray_write => process_gray_U0_stream_gray_write,
        num_pixels_dout => num_pixels_c1_dout,
        num_pixels_num_data_valid => num_pixels_c1_num_data_valid,
        num_pixels_fifo_cap => num_pixels_c1_fifo_cap,
        num_pixels_empty_n => num_pixels_c1_empty_n,
        num_pixels_read => process_gray_U0_num_pixels_read,
        num_pixels_c_din => process_gray_U0_num_pixels_c_din,
        num_pixels_c_num_data_valid => num_pixels_c_num_data_valid,
        num_pixels_c_fifo_cap => num_pixels_c_fifo_cap,
        num_pixels_c_full_n => num_pixels_c_full_n,
        num_pixels_c_write => process_gray_U0_num_pixels_c_write);

    store_gray_U0 : component rgb2gray_top_store_gray
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => store_gray_U0_ap_start,
        ap_done => store_gray_U0_ap_done,
        ap_continue => store_gray_U0_ap_continue,
        ap_idle => store_gray_U0_ap_idle,
        ap_ready => store_gray_U0_ap_ready,
        num_pixels_dout => num_pixels_c_dout,
        num_pixels_num_data_valid => num_pixels_c_num_data_valid,
        num_pixels_fifo_cap => num_pixels_c_fifo_cap,
        num_pixels_empty_n => num_pixels_c_empty_n,
        num_pixels_read => store_gray_U0_num_pixels_read,
        addr_out_dout => addr_out_c_dout,
        addr_out_num_data_valid => addr_out_c_num_data_valid,
        addr_out_fifo_cap => addr_out_c_fifo_cap,
        addr_out_empty_n => addr_out_c_empty_n,
        addr_out_read => store_gray_U0_addr_out_read,
        m_axi_out_dout => m_axi_out_c_dout,
        m_axi_out_num_data_valid => m_axi_out_c_num_data_valid,
        m_axi_out_fifo_cap => m_axi_out_c_fifo_cap,
        m_axi_out_empty_n => m_axi_out_c_empty_n,
        m_axi_out_read => store_gray_U0_m_axi_out_read,
        m_axi_gmem_out_AWVALID => store_gray_U0_m_axi_gmem_out_AWVALID,
        m_axi_gmem_out_AWREADY => gmem_out_AWREADY,
        m_axi_gmem_out_AWADDR => store_gray_U0_m_axi_gmem_out_AWADDR,
        m_axi_gmem_out_AWID => store_gray_U0_m_axi_gmem_out_AWID,
        m_axi_gmem_out_AWLEN => store_gray_U0_m_axi_gmem_out_AWLEN,
        m_axi_gmem_out_AWSIZE => store_gray_U0_m_axi_gmem_out_AWSIZE,
        m_axi_gmem_out_AWBURST => store_gray_U0_m_axi_gmem_out_AWBURST,
        m_axi_gmem_out_AWLOCK => store_gray_U0_m_axi_gmem_out_AWLOCK,
        m_axi_gmem_out_AWCACHE => store_gray_U0_m_axi_gmem_out_AWCACHE,
        m_axi_gmem_out_AWPROT => store_gray_U0_m_axi_gmem_out_AWPROT,
        m_axi_gmem_out_AWQOS => store_gray_U0_m_axi_gmem_out_AWQOS,
        m_axi_gmem_out_AWREGION => store_gray_U0_m_axi_gmem_out_AWREGION,
        m_axi_gmem_out_AWUSER => store_gray_U0_m_axi_gmem_out_AWUSER,
        m_axi_gmem_out_WVALID => store_gray_U0_m_axi_gmem_out_WVALID,
        m_axi_gmem_out_WREADY => gmem_out_WREADY,
        m_axi_gmem_out_WDATA => store_gray_U0_m_axi_gmem_out_WDATA,
        m_axi_gmem_out_WSTRB => store_gray_U0_m_axi_gmem_out_WSTRB,
        m_axi_gmem_out_WLAST => store_gray_U0_m_axi_gmem_out_WLAST,
        m_axi_gmem_out_WID => store_gray_U0_m_axi_gmem_out_WID,
        m_axi_gmem_out_WUSER => store_gray_U0_m_axi_gmem_out_WUSER,
        m_axi_gmem_out_ARVALID => store_gray_U0_m_axi_gmem_out_ARVALID,
        m_axi_gmem_out_ARREADY => ap_const_logic_0,
        m_axi_gmem_out_ARADDR => store_gray_U0_m_axi_gmem_out_ARADDR,
        m_axi_gmem_out_ARID => store_gray_U0_m_axi_gmem_out_ARID,
        m_axi_gmem_out_ARLEN => store_gray_U0_m_axi_gmem_out_ARLEN,
        m_axi_gmem_out_ARSIZE => store_gray_U0_m_axi_gmem_out_ARSIZE,
        m_axi_gmem_out_ARBURST => store_gray_U0_m_axi_gmem_out_ARBURST,
        m_axi_gmem_out_ARLOCK => store_gray_U0_m_axi_gmem_out_ARLOCK,
        m_axi_gmem_out_ARCACHE => store_gray_U0_m_axi_gmem_out_ARCACHE,
        m_axi_gmem_out_ARPROT => store_gray_U0_m_axi_gmem_out_ARPROT,
        m_axi_gmem_out_ARQOS => store_gray_U0_m_axi_gmem_out_ARQOS,
        m_axi_gmem_out_ARREGION => store_gray_U0_m_axi_gmem_out_ARREGION,
        m_axi_gmem_out_ARUSER => store_gray_U0_m_axi_gmem_out_ARUSER,
        m_axi_gmem_out_RVALID => ap_const_logic_0,
        m_axi_gmem_out_RREADY => store_gray_U0_m_axi_gmem_out_RREADY,
        m_axi_gmem_out_RDATA => ap_const_lv32_0,
        m_axi_gmem_out_RLAST => ap_const_logic_0,
        m_axi_gmem_out_RID => ap_const_lv1_0,
        m_axi_gmem_out_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem_out_RUSER => ap_const_lv1_0,
        m_axi_gmem_out_RRESP => ap_const_lv2_0,
        m_axi_gmem_out_BVALID => gmem_out_BVALID,
        m_axi_gmem_out_BREADY => store_gray_U0_m_axi_gmem_out_BREADY,
        m_axi_gmem_out_BRESP => gmem_out_BRESP,
        m_axi_gmem_out_BID => gmem_out_BID,
        m_axi_gmem_out_BUSER => gmem_out_BUSER,
        stream_gray_dout => stream_gray_dout,
        stream_gray_num_data_valid => stream_gray_num_data_valid,
        stream_gray_fifo_cap => stream_gray_fifo_cap,
        stream_gray_empty_n => stream_gray_empty_n,
        stream_gray_read => store_gray_U0_stream_gray_read);

    m_axi_out_c_U : component rgb2gray_top_fifo_w64_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_m_axi_out_c_din,
        if_full_n => m_axi_out_c_full_n,
        if_write => entry_proc_U0_m_axi_out_c_write,
        if_dout => m_axi_out_c_dout,
        if_num_data_valid => m_axi_out_c_num_data_valid,
        if_fifo_cap => m_axi_out_c_fifo_cap,
        if_empty_n => m_axi_out_c_empty_n,
        if_read => store_gray_U0_m_axi_out_read);

    addr_out_c_U : component rgb2gray_top_fifo_w32_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_addr_out_c_din,
        if_full_n => addr_out_c_full_n,
        if_write => entry_proc_U0_addr_out_c_write,
        if_dout => addr_out_c_dout,
        if_num_data_valid => addr_out_c_num_data_valid,
        if_fifo_cap => addr_out_c_fifo_cap,
        if_empty_n => addr_out_c_empty_n,
        if_read => store_gray_U0_addr_out_read);

    stream_rgb_U : component rgb2gray_top_fifo_w24_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => load_rgb_U0_stream_rgb_din,
        if_full_n => stream_rgb_full_n,
        if_write => load_rgb_U0_stream_rgb_write,
        if_dout => stream_rgb_dout,
        if_num_data_valid => stream_rgb_num_data_valid,
        if_fifo_cap => stream_rgb_fifo_cap,
        if_empty_n => stream_rgb_empty_n,
        if_read => process_gray_U0_stream_rgb_read);

    num_pixels_c1_U : component rgb2gray_top_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => load_rgb_U0_num_pixels_c1_din,
        if_full_n => num_pixels_c1_full_n,
        if_write => load_rgb_U0_num_pixels_c1_write,
        if_dout => num_pixels_c1_dout,
        if_num_data_valid => num_pixels_c1_num_data_valid,
        if_fifo_cap => num_pixels_c1_fifo_cap,
        if_empty_n => num_pixels_c1_empty_n,
        if_read => process_gray_U0_num_pixels_read);

    stream_gray_U : component rgb2gray_top_fifo_w8_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => process_gray_U0_stream_gray_din,
        if_full_n => stream_gray_full_n,
        if_write => process_gray_U0_stream_gray_write,
        if_dout => stream_gray_dout,
        if_num_data_valid => stream_gray_num_data_valid,
        if_fifo_cap => stream_gray_fifo_cap,
        if_empty_n => stream_gray_empty_n,
        if_read => store_gray_U0_stream_gray_read);

    num_pixels_c_U : component rgb2gray_top_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => process_gray_U0_num_pixels_c_din,
        if_full_n => num_pixels_c_full_n,
        if_write => process_gray_U0_num_pixels_c_write,
        if_dout => num_pixels_c_dout,
        if_num_data_valid => num_pixels_c_num_data_valid,
        if_fifo_cap => num_pixels_c_fifo_cap,
        if_empty_n => num_pixels_c_empty_n,
        if_read => store_gray_U0_num_pixels_read);

    start_for_store_gray_U0_U : component rgb2gray_top_start_for_store_gray_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_store_gray_U0_din,
        if_full_n => start_for_store_gray_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_store_gray_U0_dout,
        if_empty_n => start_for_store_gray_U0_empty_n,
        if_read => store_gray_U0_ap_ready);

    start_for_process_gray_U0_U : component rgb2gray_top_start_for_process_gray_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_process_gray_U0_din,
        if_full_n => start_for_process_gray_U0_full_n,
        if_write => load_rgb_U0_start_write,
        if_dout => start_for_process_gray_U0_dout,
        if_empty_n => start_for_process_gray_U0_empty_n,
        if_read => process_gray_U0_ap_ready);





    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_load_rgb_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_load_rgb_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_load_rgb_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_load_rgb_U0_ap_ready <= ap_sync_load_rgb_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    ap_done <= store_gray_U0_ap_done;
    ap_idle <= (store_gray_U0_ap_idle and process_gray_U0_ap_idle and load_rgb_U0_ap_idle and entry_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_load_rgb_U0_ap_ready <= (load_rgb_U0_ap_ready or ap_sync_reg_load_rgb_U0_ap_ready);
    ap_sync_ready <= (ap_sync_load_rgb_U0_ap_ready and ap_sync_entry_proc_U0_ap_ready);
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    gmem_in_RID <= ap_const_lv1_0;
    gmem_in_RLAST <= ap_const_logic_0;
    gmem_in_RRESP <= ap_const_lv2_0;
    gmem_in_RUSER <= ap_const_lv1_0;
    gmem_out_BID <= ap_const_lv1_0;
    gmem_out_BRESP <= ap_const_lv2_0;
    gmem_out_BUSER <= ap_const_lv1_0;
    load_rgb_U0_ap_continue <= ap_const_logic_1;
    load_rgb_U0_ap_start <= ((ap_sync_reg_load_rgb_U0_ap_ready xor ap_const_logic_1) and ap_start);
    process_gray_U0_ap_continue <= ap_const_logic_1;
    process_gray_U0_ap_start <= start_for_process_gray_U0_empty_n;
    start_for_process_gray_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_store_gray_U0_din <= (0=>ap_const_logic_1, others=>'-');
    store_gray_U0_ap_continue <= ap_continue;
    store_gray_U0_ap_start <= start_for_store_gray_U0_empty_n;
end behav;
