// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module rgb2gray_top_load_rgb (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem_in_AWVALID,
        m_axi_gmem_in_AWREADY,
        m_axi_gmem_in_AWADDR,
        m_axi_gmem_in_AWID,
        m_axi_gmem_in_AWLEN,
        m_axi_gmem_in_AWSIZE,
        m_axi_gmem_in_AWBURST,
        m_axi_gmem_in_AWLOCK,
        m_axi_gmem_in_AWCACHE,
        m_axi_gmem_in_AWPROT,
        m_axi_gmem_in_AWQOS,
        m_axi_gmem_in_AWREGION,
        m_axi_gmem_in_AWUSER,
        m_axi_gmem_in_WVALID,
        m_axi_gmem_in_WREADY,
        m_axi_gmem_in_WDATA,
        m_axi_gmem_in_WSTRB,
        m_axi_gmem_in_WLAST,
        m_axi_gmem_in_WID,
        m_axi_gmem_in_WUSER,
        m_axi_gmem_in_ARVALID,
        m_axi_gmem_in_ARREADY,
        m_axi_gmem_in_ARADDR,
        m_axi_gmem_in_ARID,
        m_axi_gmem_in_ARLEN,
        m_axi_gmem_in_ARSIZE,
        m_axi_gmem_in_ARBURST,
        m_axi_gmem_in_ARLOCK,
        m_axi_gmem_in_ARCACHE,
        m_axi_gmem_in_ARPROT,
        m_axi_gmem_in_ARQOS,
        m_axi_gmem_in_ARREGION,
        m_axi_gmem_in_ARUSER,
        m_axi_gmem_in_RVALID,
        m_axi_gmem_in_RREADY,
        m_axi_gmem_in_RDATA,
        m_axi_gmem_in_RLAST,
        m_axi_gmem_in_RID,
        m_axi_gmem_in_RFIFONUM,
        m_axi_gmem_in_RUSER,
        m_axi_gmem_in_RRESP,
        m_axi_gmem_in_BVALID,
        m_axi_gmem_in_BREADY,
        m_axi_gmem_in_BRESP,
        m_axi_gmem_in_BID,
        m_axi_gmem_in_BUSER,
        stream_rgb_din,
        stream_rgb_num_data_valid,
        stream_rgb_fifo_cap,
        stream_rgb_full_n,
        stream_rgb_write,
        start_out,
        start_write,
        m_axi_in,
        addr_in,
        num_pixels,
        num_pixels_c1_din,
        num_pixels_c1_num_data_valid,
        num_pixels_c1_fifo_cap,
        num_pixels_c1_full_n,
        num_pixels_c1_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_pp0_stage1 = 4'd4;
parameter    ap_ST_fsm_pp0_stage2 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_in_AWVALID;
input   m_axi_gmem_in_AWREADY;
output  [63:0] m_axi_gmem_in_AWADDR;
output  [0:0] m_axi_gmem_in_AWID;
output  [31:0] m_axi_gmem_in_AWLEN;
output  [2:0] m_axi_gmem_in_AWSIZE;
output  [1:0] m_axi_gmem_in_AWBURST;
output  [1:0] m_axi_gmem_in_AWLOCK;
output  [3:0] m_axi_gmem_in_AWCACHE;
output  [2:0] m_axi_gmem_in_AWPROT;
output  [3:0] m_axi_gmem_in_AWQOS;
output  [3:0] m_axi_gmem_in_AWREGION;
output  [0:0] m_axi_gmem_in_AWUSER;
output   m_axi_gmem_in_WVALID;
input   m_axi_gmem_in_WREADY;
output  [31:0] m_axi_gmem_in_WDATA;
output  [3:0] m_axi_gmem_in_WSTRB;
output   m_axi_gmem_in_WLAST;
output  [0:0] m_axi_gmem_in_WID;
output  [0:0] m_axi_gmem_in_WUSER;
output   m_axi_gmem_in_ARVALID;
input   m_axi_gmem_in_ARREADY;
output  [63:0] m_axi_gmem_in_ARADDR;
output  [0:0] m_axi_gmem_in_ARID;
output  [31:0] m_axi_gmem_in_ARLEN;
output  [2:0] m_axi_gmem_in_ARSIZE;
output  [1:0] m_axi_gmem_in_ARBURST;
output  [1:0] m_axi_gmem_in_ARLOCK;
output  [3:0] m_axi_gmem_in_ARCACHE;
output  [2:0] m_axi_gmem_in_ARPROT;
output  [3:0] m_axi_gmem_in_ARQOS;
output  [3:0] m_axi_gmem_in_ARREGION;
output  [0:0] m_axi_gmem_in_ARUSER;
input   m_axi_gmem_in_RVALID;
output   m_axi_gmem_in_RREADY;
input  [31:0] m_axi_gmem_in_RDATA;
input   m_axi_gmem_in_RLAST;
input  [0:0] m_axi_gmem_in_RID;
input  [8:0] m_axi_gmem_in_RFIFONUM;
input  [0:0] m_axi_gmem_in_RUSER;
input  [1:0] m_axi_gmem_in_RRESP;
input   m_axi_gmem_in_BVALID;
output   m_axi_gmem_in_BREADY;
input  [1:0] m_axi_gmem_in_BRESP;
input  [0:0] m_axi_gmem_in_BID;
input  [0:0] m_axi_gmem_in_BUSER;
output  [23:0] stream_rgb_din;
input  [4:0] stream_rgb_num_data_valid;
input  [4:0] stream_rgb_fifo_cap;
input   stream_rgb_full_n;
output   stream_rgb_write;
output   start_out;
output   start_write;
input  [63:0] m_axi_in;
input  [31:0] addr_in;
input  [31:0] num_pixels;
output  [31:0] num_pixels_c1_din;
input  [2:0] num_pixels_c1_num_data_valid;
input  [2:0] num_pixels_c1_fifo_cap;
input   num_pixels_c1_full_n;
output   num_pixels_c1_write;

reg ap_done;
reg ap_idle;
reg m_axi_gmem_in_ARVALID;
reg m_axi_gmem_in_RREADY;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [0:0] icmp_ln37_fu_293_p2;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_enable_reg_pp0_iter0;
reg   [0:0] icmp_ln37_reg_358;
reg   [0:0] icmp_ln37_reg_358_pp0_iter24_reg;
reg    ap_block_state79_pp0_stage2_iter25;
reg    ap_enable_reg_pp0_iter25;
reg    ap_block_pp0_stage2_11001;
reg    gmem_in_blk_n_R;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
reg    gmem_in_blk_n_AR;
reg   [0:0] ap_phi_mux_do_init_phi_fu_129_p6;
reg    stream_rgb_blk_n;
reg    num_pixels_c1_blk_n;
reg   [0:0] do_init_reg_124;
reg    ap_block_state3_pp0_stage1_iter0;
reg    ap_block_state3_io;
reg    ap_block_state78_pp0_stage1_iter25;
reg    ap_block_pp0_stage1_11001;
reg   [63:0] gmem_in_addr_rewind_idx_reg_141;
reg   [31:0] i_reg_171;
reg   [63:0] gmem_in_addr_phi_idx_reg_185;
reg   [31:0] num_pixels6_phi_reg_197;
wire  signed [63:0] sext_ln37_fu_270_p1;
wire   [31:0] i_3_fu_287_p2;
reg   [31:0] i_3_reg_353;
reg   [0:0] icmp_ln37_reg_358_pp0_iter1_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter2_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter3_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter4_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter5_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter6_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter7_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter8_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter9_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter10_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter11_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter12_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter13_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter14_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter15_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter16_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter17_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter18_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter19_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter20_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter21_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter22_reg;
reg   [0:0] icmp_ln37_reg_358_pp0_iter23_reg;
wire   [7:0] r_fu_299_p1;
reg   [7:0] r_reg_362;
reg    ap_block_state77_pp0_stage0_iter25;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] g_fu_305_p1;
reg   [7:0] g_reg_367;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_block_state1;
reg   [63:0] ap_phi_mux_gmem_in_addr_rewind_idx_phi_fu_145_p6;
reg   [31:0] ap_phi_mux_i_phi_fu_175_p6;
reg   [63:0] ap_phi_reg_pp0_iter0_gmem_in_addr_phi_idx_reg_185;
reg   [31:0] ap_phi_reg_pp0_iter0_num_pixels6_phi_reg_197;
reg    ap_block_pp0_stage1_01001;
reg    num_pixels_c1_write_local;
wire   [23:0] or_ln52_3_fu_313_p4;
reg    ap_block_pp0_stage2_01001;
reg    stream_rgb_write_local;
wire   [33:0] p_shl_fu_223_p3;
wire   [33:0] zext_ln37_fu_219_p1;
wire   [33:0] sub_ln37_fu_231_p2;
wire   [33:0] shl_ln_fu_242_p3;
wire   [63:0] zext_ln37_2_fu_250_p1;
wire   [63:0] add_ln37_fu_254_p2;
wire   [61:0] trunc_ln_fu_260_p4;
wire   [7:0] b_fu_309_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage1_subdone;
reg    ap_idle_pp0_0to24;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [63:0] m_axi_gmem_in_ARLEN0;
reg    ap_condition_454;
reg    ap_condition_466;
reg    ap_condition_473;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln37_reg_358_pp0_iter24_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter25 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= real_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_enable_reg_pp0_iter25 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_473)) begin
        if ((ap_phi_mux_do_init_phi_fu_129_p6 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_gmem_in_addr_phi_idx_reg_185 <= ap_phi_mux_gmem_in_addr_rewind_idx_phi_fu_145_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_129_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_gmem_in_addr_phi_idx_reg_185 <= sext_ln37_fu_270_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_473)) begin
        if ((ap_phi_mux_do_init_phi_fu_129_p6 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_num_pixels6_phi_reg_197 <= num_pixels6_phi_reg_197;
        end else if ((ap_phi_mux_do_init_phi_fu_129_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_num_pixels6_phi_reg_197 <= num_pixels;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_358 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        do_init_reg_124 <= 1'd0;
    end else if ((((icmp_ln37_reg_358 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        do_init_reg_124 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_358 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        gmem_in_addr_rewind_idx_reg_141 <= gmem_in_addr_phi_idx_reg_185;
    end else if ((((icmp_ln37_reg_358 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        gmem_in_addr_rewind_idx_reg_141 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_358 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        i_reg_171 <= i_3_reg_353;
    end else if ((((icmp_ln37_reg_358 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        i_reg_171 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        g_reg_367 <= g_fu_305_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        gmem_in_addr_phi_idx_reg_185 <= ap_phi_reg_pp0_iter0_gmem_in_addr_phi_idx_reg_185;
        i_3_reg_353 <= i_3_fu_287_p2;
        num_pixels6_phi_reg_197 <= ap_phi_reg_pp0_iter0_num_pixels6_phi_reg_197;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        icmp_ln37_reg_358 <= icmp_ln37_fu_293_p2;
        icmp_ln37_reg_358_pp0_iter10_reg <= icmp_ln37_reg_358_pp0_iter9_reg;
        icmp_ln37_reg_358_pp0_iter11_reg <= icmp_ln37_reg_358_pp0_iter10_reg;
        icmp_ln37_reg_358_pp0_iter12_reg <= icmp_ln37_reg_358_pp0_iter11_reg;
        icmp_ln37_reg_358_pp0_iter13_reg <= icmp_ln37_reg_358_pp0_iter12_reg;
        icmp_ln37_reg_358_pp0_iter14_reg <= icmp_ln37_reg_358_pp0_iter13_reg;
        icmp_ln37_reg_358_pp0_iter15_reg <= icmp_ln37_reg_358_pp0_iter14_reg;
        icmp_ln37_reg_358_pp0_iter16_reg <= icmp_ln37_reg_358_pp0_iter15_reg;
        icmp_ln37_reg_358_pp0_iter17_reg <= icmp_ln37_reg_358_pp0_iter16_reg;
        icmp_ln37_reg_358_pp0_iter18_reg <= icmp_ln37_reg_358_pp0_iter17_reg;
        icmp_ln37_reg_358_pp0_iter19_reg <= icmp_ln37_reg_358_pp0_iter18_reg;
        icmp_ln37_reg_358_pp0_iter1_reg <= icmp_ln37_reg_358;
        icmp_ln37_reg_358_pp0_iter20_reg <= icmp_ln37_reg_358_pp0_iter19_reg;
        icmp_ln37_reg_358_pp0_iter21_reg <= icmp_ln37_reg_358_pp0_iter20_reg;
        icmp_ln37_reg_358_pp0_iter22_reg <= icmp_ln37_reg_358_pp0_iter21_reg;
        icmp_ln37_reg_358_pp0_iter23_reg <= icmp_ln37_reg_358_pp0_iter22_reg;
        icmp_ln37_reg_358_pp0_iter24_reg <= icmp_ln37_reg_358_pp0_iter23_reg;
        icmp_ln37_reg_358_pp0_iter2_reg <= icmp_ln37_reg_358_pp0_iter1_reg;
        icmp_ln37_reg_358_pp0_iter3_reg <= icmp_ln37_reg_358_pp0_iter2_reg;
        icmp_ln37_reg_358_pp0_iter4_reg <= icmp_ln37_reg_358_pp0_iter3_reg;
        icmp_ln37_reg_358_pp0_iter5_reg <= icmp_ln37_reg_358_pp0_iter4_reg;
        icmp_ln37_reg_358_pp0_iter6_reg <= icmp_ln37_reg_358_pp0_iter5_reg;
        icmp_ln37_reg_358_pp0_iter7_reg <= icmp_ln37_reg_358_pp0_iter6_reg;
        icmp_ln37_reg_358_pp0_iter8_reg <= icmp_ln37_reg_358_pp0_iter7_reg;
        icmp_ln37_reg_358_pp0_iter9_reg <= icmp_ln37_reg_358_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_reg_362 <= r_fu_299_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_358_pp0_iter24_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter25 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = real_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to24 = 1'b1;
    end else begin
        ap_idle_pp0_0to24 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_454)) begin
        if ((icmp_ln37_reg_358 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_129_p6 = 1'd1;
        end else if ((icmp_ln37_reg_358 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_129_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_129_p6 = do_init_reg_124;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_129_p6 = do_init_reg_124;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_454)) begin
        if ((icmp_ln37_reg_358 == 1'd1)) begin
            ap_phi_mux_gmem_in_addr_rewind_idx_phi_fu_145_p6 = 64'd0;
        end else if ((icmp_ln37_reg_358 == 1'd0)) begin
            ap_phi_mux_gmem_in_addr_rewind_idx_phi_fu_145_p6 = gmem_in_addr_phi_idx_reg_185;
        end else begin
            ap_phi_mux_gmem_in_addr_rewind_idx_phi_fu_145_p6 = gmem_in_addr_rewind_idx_reg_141;
        end
    end else begin
        ap_phi_mux_gmem_in_addr_rewind_idx_phi_fu_145_p6 = gmem_in_addr_rewind_idx_reg_141;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_466)) begin
        if ((icmp_ln37_reg_358 == 1'd1)) begin
            ap_phi_mux_i_phi_fu_175_p6 = 32'd0;
        end else if ((icmp_ln37_reg_358 == 1'd0)) begin
            ap_phi_mux_i_phi_fu_175_p6 = i_3_reg_353;
        end else begin
            ap_phi_mux_i_phi_fu_175_p6 = i_reg_171;
        end
    end else begin
        ap_phi_mux_i_phi_fu_175_p6 = i_reg_171;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to24 == 1'b1) & (real_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_phi_mux_do_init_phi_fu_129_p6 == 1'd1) & (1'b0 == ap_block_pp0_stage1))) begin
        gmem_in_blk_n_AR = m_axi_gmem_in_ARREADY;
    end else begin
        gmem_in_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter25 == 1'b1)) | ((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter25 == 1'b1)) | ((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter25 == 1'b1)))) begin
        gmem_in_blk_n_R = m_axi_gmem_in_RVALID;
    end else begin
        gmem_in_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_fu_293_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_phi_mux_do_init_phi_fu_129_p6 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        m_axi_gmem_in_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_in_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter25 == 1'b1)) | ((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter25 == 1'b1)) | ((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter25 == 1'b1)))) begin
        m_axi_gmem_in_RREADY = 1'b1;
    end else begin
        m_axi_gmem_in_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_phi_mux_do_init_phi_fu_129_p6 == 1'd1) & (1'b0 == ap_block_pp0_stage1))) begin
        num_pixels_c1_blk_n = num_pixels_c1_full_n;
    end else begin
        num_pixels_c1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_phi_mux_do_init_phi_fu_129_p6 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        num_pixels_c1_write_local = 1'b1;
    end else begin
        num_pixels_c1_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter25 == 1'b1))) begin
        stream_rgb_blk_n = stream_rgb_full_n;
    end else begin
        stream_rgb_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter25 == 1'b1))) begin
        stream_rgb_write_local = 1'b1;
    end else begin
        stream_rgb_write_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln37_fu_254_p2 = (zext_ln37_2_fu_250_p1 + m_axi_in);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((1'b1 == ap_block_state77_pp0_stage0_iter25) & (ap_enable_reg_pp0_iter25 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((1'b1 == ap_block_state77_pp0_stage0_iter25) & (ap_enable_reg_pp0_iter25 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage1_iter0)) | ((1'b1 == ap_block_state78_pp0_stage1_iter25) & (ap_enable_reg_pp0_iter25 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage1_iter0))) | ((1'b1 == ap_block_state78_pp0_stage1_iter25) & (ap_enable_reg_pp0_iter25 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage1_iter0))) | ((1'b1 == ap_block_state78_pp0_stage1_iter25) & (ap_enable_reg_pp0_iter25 == 1'b1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001 = ((1'b1 == ap_block_state79_pp0_stage2_iter25) & (ap_enable_reg_pp0_iter25 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((1'b1 == ap_block_state79_pp0_stage2_iter25) & (ap_enable_reg_pp0_iter25 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((1'b1 == ap_block_state79_pp0_stage2_iter25) & (ap_enable_reg_pp0_iter25 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((m_axi_gmem_in_ARREADY == 1'b0) & (ap_phi_mux_do_init_phi_fu_129_p6 == 1'd1));
end

always @ (*) begin
    ap_block_state3_pp0_stage1_iter0 = ((ap_phi_mux_do_init_phi_fu_129_p6 == 1'd1) & (num_pixels_c1_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state77_pp0_stage0_iter25 = ((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (m_axi_gmem_in_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state78_pp0_stage1_iter25 = ((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (m_axi_gmem_in_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state79_pp0_stage2_iter25 = (((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (m_axi_gmem_in_RVALID == 1'b0)) | ((icmp_ln37_reg_358_pp0_iter24_reg == 1'd0) & (stream_rgb_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_454 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1));
end

always @ (*) begin
    ap_condition_466 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2));
end

always @ (*) begin
    ap_condition_473 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign b_fu_309_p1 = m_axi_gmem_in_RDATA[7:0];

assign g_fu_305_p1 = m_axi_gmem_in_RDATA[7:0];

assign i_3_fu_287_p2 = (ap_phi_mux_i_phi_fu_175_p6 + 32'd1);

assign icmp_ln37_fu_293_p2 = ((ap_phi_mux_i_phi_fu_175_p6 == ap_phi_reg_pp0_iter0_num_pixels6_phi_reg_197) ? 1'b1 : 1'b0);

assign m_axi_gmem_in_ARADDR = sext_ln37_fu_270_p1;

assign m_axi_gmem_in_ARBURST = 2'd0;

assign m_axi_gmem_in_ARCACHE = 4'd0;

assign m_axi_gmem_in_ARID = 1'd0;

assign m_axi_gmem_in_ARLEN = m_axi_gmem_in_ARLEN0;

assign m_axi_gmem_in_ARLEN0 = sub_ln37_fu_231_p2;

assign m_axi_gmem_in_ARLOCK = 2'd0;

assign m_axi_gmem_in_ARPROT = 3'd0;

assign m_axi_gmem_in_ARQOS = 4'd0;

assign m_axi_gmem_in_ARREGION = 4'd0;

assign m_axi_gmem_in_ARSIZE = 3'd0;

assign m_axi_gmem_in_ARUSER = 1'd0;

assign m_axi_gmem_in_AWADDR = 64'd0;

assign m_axi_gmem_in_AWBURST = 2'd0;

assign m_axi_gmem_in_AWCACHE = 4'd0;

assign m_axi_gmem_in_AWID = 1'd0;

assign m_axi_gmem_in_AWLEN = 32'd0;

assign m_axi_gmem_in_AWLOCK = 2'd0;

assign m_axi_gmem_in_AWPROT = 3'd0;

assign m_axi_gmem_in_AWQOS = 4'd0;

assign m_axi_gmem_in_AWREGION = 4'd0;

assign m_axi_gmem_in_AWSIZE = 3'd0;

assign m_axi_gmem_in_AWUSER = 1'd0;

assign m_axi_gmem_in_AWVALID = 1'b0;

assign m_axi_gmem_in_BREADY = 1'b0;

assign m_axi_gmem_in_WDATA = 32'd0;

assign m_axi_gmem_in_WID = 1'd0;

assign m_axi_gmem_in_WLAST = 1'b0;

assign m_axi_gmem_in_WSTRB = 4'd0;

assign m_axi_gmem_in_WUSER = 1'd0;

assign m_axi_gmem_in_WVALID = 1'b0;

assign num_pixels_c1_din = num_pixels;

assign num_pixels_c1_write = num_pixels_c1_write_local;

assign or_ln52_3_fu_313_p4 = {{{b_fu_309_p1}, {g_reg_367}}, {r_reg_362}};

assign p_shl_fu_223_p3 = {{num_pixels}, {2'd0}};

assign r_fu_299_p1 = m_axi_gmem_in_RDATA[7:0];

assign sext_ln37_fu_270_p1 = $signed(trunc_ln_fu_260_p4);

assign shl_ln_fu_242_p3 = {{addr_in}, {2'd0}};

assign start_out = real_start;

assign stream_rgb_din = or_ln52_3_fu_313_p4;

assign stream_rgb_write = stream_rgb_write_local;

assign sub_ln37_fu_231_p2 = (p_shl_fu_223_p3 - zext_ln37_fu_219_p1);

assign trunc_ln_fu_260_p4 = {{add_ln37_fu_254_p2[63:2]}};

assign zext_ln37_2_fu_250_p1 = shl_ln_fu_242_p3;

assign zext_ln37_fu_219_p1 = num_pixels;

endmodule //rgb2gray_top_load_rgb
