// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rgb2gray_top_rgb2gray_top,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.920000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=5377,HLS_SYN_LUT=6500,HLS_VERSION=2024_1}" *)

module rgb2gray_top (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem_in_AWVALID,
        m_axi_gmem_in_AWREADY,
        m_axi_gmem_in_AWADDR,
        m_axi_gmem_in_AWID,
        m_axi_gmem_in_AWLEN,
        m_axi_gmem_in_AWSIZE,
        m_axi_gmem_in_AWBURST,
        m_axi_gmem_in_AWLOCK,
        m_axi_gmem_in_AWCACHE,
        m_axi_gmem_in_AWPROT,
        m_axi_gmem_in_AWQOS,
        m_axi_gmem_in_AWREGION,
        m_axi_gmem_in_AWUSER,
        m_axi_gmem_in_WVALID,
        m_axi_gmem_in_WREADY,
        m_axi_gmem_in_WDATA,
        m_axi_gmem_in_WSTRB,
        m_axi_gmem_in_WLAST,
        m_axi_gmem_in_WID,
        m_axi_gmem_in_WUSER,
        m_axi_gmem_in_ARVALID,
        m_axi_gmem_in_ARREADY,
        m_axi_gmem_in_ARADDR,
        m_axi_gmem_in_ARID,
        m_axi_gmem_in_ARLEN,
        m_axi_gmem_in_ARSIZE,
        m_axi_gmem_in_ARBURST,
        m_axi_gmem_in_ARLOCK,
        m_axi_gmem_in_ARCACHE,
        m_axi_gmem_in_ARPROT,
        m_axi_gmem_in_ARQOS,
        m_axi_gmem_in_ARREGION,
        m_axi_gmem_in_ARUSER,
        m_axi_gmem_in_RVALID,
        m_axi_gmem_in_RREADY,
        m_axi_gmem_in_RDATA,
        m_axi_gmem_in_RLAST,
        m_axi_gmem_in_RID,
        m_axi_gmem_in_RUSER,
        m_axi_gmem_in_RRESP,
        m_axi_gmem_in_BVALID,
        m_axi_gmem_in_BREADY,
        m_axi_gmem_in_BRESP,
        m_axi_gmem_in_BID,
        m_axi_gmem_in_BUSER,
        m_axi_gmem_out_AWVALID,
        m_axi_gmem_out_AWREADY,
        m_axi_gmem_out_AWADDR,
        m_axi_gmem_out_AWID,
        m_axi_gmem_out_AWLEN,
        m_axi_gmem_out_AWSIZE,
        m_axi_gmem_out_AWBURST,
        m_axi_gmem_out_AWLOCK,
        m_axi_gmem_out_AWCACHE,
        m_axi_gmem_out_AWPROT,
        m_axi_gmem_out_AWQOS,
        m_axi_gmem_out_AWREGION,
        m_axi_gmem_out_AWUSER,
        m_axi_gmem_out_WVALID,
        m_axi_gmem_out_WREADY,
        m_axi_gmem_out_WDATA,
        m_axi_gmem_out_WSTRB,
        m_axi_gmem_out_WLAST,
        m_axi_gmem_out_WID,
        m_axi_gmem_out_WUSER,
        m_axi_gmem_out_ARVALID,
        m_axi_gmem_out_ARREADY,
        m_axi_gmem_out_ARADDR,
        m_axi_gmem_out_ARID,
        m_axi_gmem_out_ARLEN,
        m_axi_gmem_out_ARSIZE,
        m_axi_gmem_out_ARBURST,
        m_axi_gmem_out_ARLOCK,
        m_axi_gmem_out_ARCACHE,
        m_axi_gmem_out_ARPROT,
        m_axi_gmem_out_ARQOS,
        m_axi_gmem_out_ARREGION,
        m_axi_gmem_out_ARUSER,
        m_axi_gmem_out_RVALID,
        m_axi_gmem_out_RREADY,
        m_axi_gmem_out_RDATA,
        m_axi_gmem_out_RLAST,
        m_axi_gmem_out_RID,
        m_axi_gmem_out_RUSER,
        m_axi_gmem_out_RRESP,
        m_axi_gmem_out_BVALID,
        m_axi_gmem_out_BREADY,
        m_axi_gmem_out_BRESP,
        m_axi_gmem_out_BID,
        m_axi_gmem_out_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_IN_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_IN_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_IN_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_IN_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_IN_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_OUT_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_OUT_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_OUT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_OUT_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_OUT_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_IN_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_OUT_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem_in_AWVALID;
input   m_axi_gmem_in_AWREADY;
output  [C_M_AXI_GMEM_IN_ADDR_WIDTH - 1:0] m_axi_gmem_in_AWADDR;
output  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_AWID;
output  [7:0] m_axi_gmem_in_AWLEN;
output  [2:0] m_axi_gmem_in_AWSIZE;
output  [1:0] m_axi_gmem_in_AWBURST;
output  [1:0] m_axi_gmem_in_AWLOCK;
output  [3:0] m_axi_gmem_in_AWCACHE;
output  [2:0] m_axi_gmem_in_AWPROT;
output  [3:0] m_axi_gmem_in_AWQOS;
output  [3:0] m_axi_gmem_in_AWREGION;
output  [C_M_AXI_GMEM_IN_AWUSER_WIDTH - 1:0] m_axi_gmem_in_AWUSER;
output   m_axi_gmem_in_WVALID;
input   m_axi_gmem_in_WREADY;
output  [C_M_AXI_GMEM_IN_DATA_WIDTH - 1:0] m_axi_gmem_in_WDATA;
output  [C_M_AXI_GMEM_IN_WSTRB_WIDTH - 1:0] m_axi_gmem_in_WSTRB;
output   m_axi_gmem_in_WLAST;
output  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_WID;
output  [C_M_AXI_GMEM_IN_WUSER_WIDTH - 1:0] m_axi_gmem_in_WUSER;
output   m_axi_gmem_in_ARVALID;
input   m_axi_gmem_in_ARREADY;
output  [C_M_AXI_GMEM_IN_ADDR_WIDTH - 1:0] m_axi_gmem_in_ARADDR;
output  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_ARID;
output  [7:0] m_axi_gmem_in_ARLEN;
output  [2:0] m_axi_gmem_in_ARSIZE;
output  [1:0] m_axi_gmem_in_ARBURST;
output  [1:0] m_axi_gmem_in_ARLOCK;
output  [3:0] m_axi_gmem_in_ARCACHE;
output  [2:0] m_axi_gmem_in_ARPROT;
output  [3:0] m_axi_gmem_in_ARQOS;
output  [3:0] m_axi_gmem_in_ARREGION;
output  [C_M_AXI_GMEM_IN_ARUSER_WIDTH - 1:0] m_axi_gmem_in_ARUSER;
input   m_axi_gmem_in_RVALID;
output   m_axi_gmem_in_RREADY;
input  [C_M_AXI_GMEM_IN_DATA_WIDTH - 1:0] m_axi_gmem_in_RDATA;
input   m_axi_gmem_in_RLAST;
input  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_RID;
input  [C_M_AXI_GMEM_IN_RUSER_WIDTH - 1:0] m_axi_gmem_in_RUSER;
input  [1:0] m_axi_gmem_in_RRESP;
input   m_axi_gmem_in_BVALID;
output   m_axi_gmem_in_BREADY;
input  [1:0] m_axi_gmem_in_BRESP;
input  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_BID;
input  [C_M_AXI_GMEM_IN_BUSER_WIDTH - 1:0] m_axi_gmem_in_BUSER;
output   m_axi_gmem_out_AWVALID;
input   m_axi_gmem_out_AWREADY;
output  [C_M_AXI_GMEM_OUT_ADDR_WIDTH - 1:0] m_axi_gmem_out_AWADDR;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_AWID;
output  [7:0] m_axi_gmem_out_AWLEN;
output  [2:0] m_axi_gmem_out_AWSIZE;
output  [1:0] m_axi_gmem_out_AWBURST;
output  [1:0] m_axi_gmem_out_AWLOCK;
output  [3:0] m_axi_gmem_out_AWCACHE;
output  [2:0] m_axi_gmem_out_AWPROT;
output  [3:0] m_axi_gmem_out_AWQOS;
output  [3:0] m_axi_gmem_out_AWREGION;
output  [C_M_AXI_GMEM_OUT_AWUSER_WIDTH - 1:0] m_axi_gmem_out_AWUSER;
output   m_axi_gmem_out_WVALID;
input   m_axi_gmem_out_WREADY;
output  [C_M_AXI_GMEM_OUT_DATA_WIDTH - 1:0] m_axi_gmem_out_WDATA;
output  [C_M_AXI_GMEM_OUT_WSTRB_WIDTH - 1:0] m_axi_gmem_out_WSTRB;
output   m_axi_gmem_out_WLAST;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_WID;
output  [C_M_AXI_GMEM_OUT_WUSER_WIDTH - 1:0] m_axi_gmem_out_WUSER;
output   m_axi_gmem_out_ARVALID;
input   m_axi_gmem_out_ARREADY;
output  [C_M_AXI_GMEM_OUT_ADDR_WIDTH - 1:0] m_axi_gmem_out_ARADDR;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_ARID;
output  [7:0] m_axi_gmem_out_ARLEN;
output  [2:0] m_axi_gmem_out_ARSIZE;
output  [1:0] m_axi_gmem_out_ARBURST;
output  [1:0] m_axi_gmem_out_ARLOCK;
output  [3:0] m_axi_gmem_out_ARCACHE;
output  [2:0] m_axi_gmem_out_ARPROT;
output  [3:0] m_axi_gmem_out_ARQOS;
output  [3:0] m_axi_gmem_out_ARREGION;
output  [C_M_AXI_GMEM_OUT_ARUSER_WIDTH - 1:0] m_axi_gmem_out_ARUSER;
input   m_axi_gmem_out_RVALID;
output   m_axi_gmem_out_RREADY;
input  [C_M_AXI_GMEM_OUT_DATA_WIDTH - 1:0] m_axi_gmem_out_RDATA;
input   m_axi_gmem_out_RLAST;
input  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_RID;
input  [C_M_AXI_GMEM_OUT_RUSER_WIDTH - 1:0] m_axi_gmem_out_RUSER;
input  [1:0] m_axi_gmem_out_RRESP;
input   m_axi_gmem_out_BVALID;
output   m_axi_gmem_out_BREADY;
input  [1:0] m_axi_gmem_out_BRESP;
input  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_BID;
input  [C_M_AXI_GMEM_OUT_BUSER_WIDTH - 1:0] m_axi_gmem_out_BUSER;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [63:0] m_axi_in;
wire   [63:0] m_axi_out;
wire   [31:0] addr_in;
wire   [31:0] addr_out;
wire   [31:0] num_pixels;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    gmem_in_AWREADY;
wire    gmem_in_WREADY;
wire    gmem_in_ARREADY;
wire    gmem_in_RVALID;
wire   [31:0] gmem_in_RDATA;
wire    gmem_in_RLAST;
wire   [0:0] gmem_in_RID;
wire   [8:0] gmem_in_RFIFONUM;
wire   [0:0] gmem_in_RUSER;
wire   [1:0] gmem_in_RRESP;
wire    gmem_in_BVALID;
wire    gmem_out_AWREADY;
wire    gmem_out_WREADY;
wire    gmem_out_ARREADY;
wire    gmem_out_RVALID;
wire   [31:0] gmem_out_RDATA;
wire   [8:0] gmem_out_RFIFONUM;
wire    gmem_out_BVALID;
wire   [1:0] gmem_out_BRESP;
wire   [0:0] gmem_out_BID;
wire   [0:0] gmem_out_BUSER;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [63:0] entry_proc_U0_m_axi_out_c_din;
wire    entry_proc_U0_m_axi_out_c_write;
wire   [31:0] entry_proc_U0_addr_out_c_din;
wire    entry_proc_U0_addr_out_c_write;
wire    load_rgb_U0_ap_start;
wire    load_rgb_U0_ap_done;
wire    load_rgb_U0_ap_continue;
wire    load_rgb_U0_ap_idle;
wire    load_rgb_U0_ap_ready;
wire    load_rgb_U0_m_axi_gmem_in_AWVALID;
wire   [63:0] load_rgb_U0_m_axi_gmem_in_AWADDR;
wire   [0:0] load_rgb_U0_m_axi_gmem_in_AWID;
wire   [31:0] load_rgb_U0_m_axi_gmem_in_AWLEN;
wire   [2:0] load_rgb_U0_m_axi_gmem_in_AWSIZE;
wire   [1:0] load_rgb_U0_m_axi_gmem_in_AWBURST;
wire   [1:0] load_rgb_U0_m_axi_gmem_in_AWLOCK;
wire   [3:0] load_rgb_U0_m_axi_gmem_in_AWCACHE;
wire   [2:0] load_rgb_U0_m_axi_gmem_in_AWPROT;
wire   [3:0] load_rgb_U0_m_axi_gmem_in_AWQOS;
wire   [3:0] load_rgb_U0_m_axi_gmem_in_AWREGION;
wire   [0:0] load_rgb_U0_m_axi_gmem_in_AWUSER;
wire    load_rgb_U0_m_axi_gmem_in_WVALID;
wire   [31:0] load_rgb_U0_m_axi_gmem_in_WDATA;
wire   [3:0] load_rgb_U0_m_axi_gmem_in_WSTRB;
wire    load_rgb_U0_m_axi_gmem_in_WLAST;
wire   [0:0] load_rgb_U0_m_axi_gmem_in_WID;
wire   [0:0] load_rgb_U0_m_axi_gmem_in_WUSER;
wire    load_rgb_U0_m_axi_gmem_in_ARVALID;
wire   [63:0] load_rgb_U0_m_axi_gmem_in_ARADDR;
wire   [0:0] load_rgb_U0_m_axi_gmem_in_ARID;
wire   [31:0] load_rgb_U0_m_axi_gmem_in_ARLEN;
wire   [2:0] load_rgb_U0_m_axi_gmem_in_ARSIZE;
wire   [1:0] load_rgb_U0_m_axi_gmem_in_ARBURST;
wire   [1:0] load_rgb_U0_m_axi_gmem_in_ARLOCK;
wire   [3:0] load_rgb_U0_m_axi_gmem_in_ARCACHE;
wire   [2:0] load_rgb_U0_m_axi_gmem_in_ARPROT;
wire   [3:0] load_rgb_U0_m_axi_gmem_in_ARQOS;
wire   [3:0] load_rgb_U0_m_axi_gmem_in_ARREGION;
wire   [0:0] load_rgb_U0_m_axi_gmem_in_ARUSER;
wire    load_rgb_U0_m_axi_gmem_in_RREADY;
wire    load_rgb_U0_m_axi_gmem_in_BREADY;
wire   [23:0] load_rgb_U0_stream_rgb_din;
wire    load_rgb_U0_stream_rgb_write;
wire    load_rgb_U0_start_out;
wire    load_rgb_U0_start_write;
wire   [31:0] load_rgb_U0_num_pixels_c1_din;
wire    load_rgb_U0_num_pixels_c1_write;
wire    process_gray_U0_ap_start;
wire    process_gray_U0_ap_done;
wire    process_gray_U0_ap_continue;
wire    process_gray_U0_ap_idle;
wire    process_gray_U0_ap_ready;
wire    process_gray_U0_stream_rgb_read;
wire   [7:0] process_gray_U0_stream_gray_din;
wire    process_gray_U0_stream_gray_write;
wire    process_gray_U0_num_pixels_read;
wire   [31:0] process_gray_U0_num_pixels_c_din;
wire    process_gray_U0_num_pixels_c_write;
wire    store_gray_U0_ap_start;
wire    store_gray_U0_ap_done;
wire    store_gray_U0_ap_continue;
wire    store_gray_U0_ap_idle;
wire    store_gray_U0_ap_ready;
wire    store_gray_U0_num_pixels_read;
wire    store_gray_U0_addr_out_read;
wire    store_gray_U0_m_axi_out_read;
wire    store_gray_U0_m_axi_gmem_out_AWVALID;
wire   [63:0] store_gray_U0_m_axi_gmem_out_AWADDR;
wire   [0:0] store_gray_U0_m_axi_gmem_out_AWID;
wire   [31:0] store_gray_U0_m_axi_gmem_out_AWLEN;
wire   [2:0] store_gray_U0_m_axi_gmem_out_AWSIZE;
wire   [1:0] store_gray_U0_m_axi_gmem_out_AWBURST;
wire   [1:0] store_gray_U0_m_axi_gmem_out_AWLOCK;
wire   [3:0] store_gray_U0_m_axi_gmem_out_AWCACHE;
wire   [2:0] store_gray_U0_m_axi_gmem_out_AWPROT;
wire   [3:0] store_gray_U0_m_axi_gmem_out_AWQOS;
wire   [3:0] store_gray_U0_m_axi_gmem_out_AWREGION;
wire   [0:0] store_gray_U0_m_axi_gmem_out_AWUSER;
wire    store_gray_U0_m_axi_gmem_out_WVALID;
wire   [31:0] store_gray_U0_m_axi_gmem_out_WDATA;
wire   [3:0] store_gray_U0_m_axi_gmem_out_WSTRB;
wire    store_gray_U0_m_axi_gmem_out_WLAST;
wire   [0:0] store_gray_U0_m_axi_gmem_out_WID;
wire   [0:0] store_gray_U0_m_axi_gmem_out_WUSER;
wire    store_gray_U0_m_axi_gmem_out_ARVALID;
wire   [63:0] store_gray_U0_m_axi_gmem_out_ARADDR;
wire   [0:0] store_gray_U0_m_axi_gmem_out_ARID;
wire   [31:0] store_gray_U0_m_axi_gmem_out_ARLEN;
wire   [2:0] store_gray_U0_m_axi_gmem_out_ARSIZE;
wire   [1:0] store_gray_U0_m_axi_gmem_out_ARBURST;
wire   [1:0] store_gray_U0_m_axi_gmem_out_ARLOCK;
wire   [3:0] store_gray_U0_m_axi_gmem_out_ARCACHE;
wire   [2:0] store_gray_U0_m_axi_gmem_out_ARPROT;
wire   [3:0] store_gray_U0_m_axi_gmem_out_ARQOS;
wire   [3:0] store_gray_U0_m_axi_gmem_out_ARREGION;
wire   [0:0] store_gray_U0_m_axi_gmem_out_ARUSER;
wire    store_gray_U0_m_axi_gmem_out_RREADY;
wire    store_gray_U0_m_axi_gmem_out_BREADY;
wire    store_gray_U0_stream_gray_read;
wire    m_axi_out_c_full_n;
wire   [63:0] m_axi_out_c_dout;
wire   [2:0] m_axi_out_c_num_data_valid;
wire   [2:0] m_axi_out_c_fifo_cap;
wire    m_axi_out_c_empty_n;
wire    addr_out_c_full_n;
wire   [31:0] addr_out_c_dout;
wire   [2:0] addr_out_c_num_data_valid;
wire   [2:0] addr_out_c_fifo_cap;
wire    addr_out_c_empty_n;
wire    stream_rgb_full_n;
wire   [23:0] stream_rgb_dout;
wire   [4:0] stream_rgb_num_data_valid;
wire   [4:0] stream_rgb_fifo_cap;
wire    stream_rgb_empty_n;
wire    num_pixels_c1_full_n;
wire   [31:0] num_pixels_c1_dout;
wire   [2:0] num_pixels_c1_num_data_valid;
wire   [2:0] num_pixels_c1_fifo_cap;
wire    num_pixels_c1_empty_n;
wire    stream_gray_full_n;
wire   [7:0] stream_gray_dout;
wire   [4:0] stream_gray_num_data_valid;
wire   [4:0] stream_gray_fifo_cap;
wire    stream_gray_empty_n;
wire    num_pixels_c_full_n;
wire   [31:0] num_pixels_c_dout;
wire   [2:0] num_pixels_c_num_data_valid;
wire   [2:0] num_pixels_c_fifo_cap;
wire    num_pixels_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_load_rgb_U0_ap_ready;
wire    ap_sync_load_rgb_U0_ap_ready;
wire   [0:0] start_for_store_gray_U0_din;
wire    start_for_store_gray_U0_full_n;
wire   [0:0] start_for_store_gray_U0_dout;
wire    start_for_store_gray_U0_empty_n;
wire   [0:0] start_for_process_gray_U0_din;
wire    start_for_process_gray_U0_full_n;
wire   [0:0] start_for_process_gray_U0_dout;
wire    start_for_process_gray_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_load_rgb_U0_ap_ready = 1'b0;
end

rgb2gray_top_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .m_axi_in(m_axi_in),
    .m_axi_out(m_axi_out),
    .addr_in(addr_in),
    .addr_out(addr_out),
    .num_pixels(num_pixels),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

rgb2gray_top_gmem_in_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 73 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_IN_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_IN_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_IN_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_IN_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_IN_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_IN_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_IN_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_IN_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_IN_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_IN_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_IN_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_in_m_axi_U(
    .AWVALID(m_axi_gmem_in_AWVALID),
    .AWREADY(m_axi_gmem_in_AWREADY),
    .AWADDR(m_axi_gmem_in_AWADDR),
    .AWID(m_axi_gmem_in_AWID),
    .AWLEN(m_axi_gmem_in_AWLEN),
    .AWSIZE(m_axi_gmem_in_AWSIZE),
    .AWBURST(m_axi_gmem_in_AWBURST),
    .AWLOCK(m_axi_gmem_in_AWLOCK),
    .AWCACHE(m_axi_gmem_in_AWCACHE),
    .AWPROT(m_axi_gmem_in_AWPROT),
    .AWQOS(m_axi_gmem_in_AWQOS),
    .AWREGION(m_axi_gmem_in_AWREGION),
    .AWUSER(m_axi_gmem_in_AWUSER),
    .WVALID(m_axi_gmem_in_WVALID),
    .WREADY(m_axi_gmem_in_WREADY),
    .WDATA(m_axi_gmem_in_WDATA),
    .WSTRB(m_axi_gmem_in_WSTRB),
    .WLAST(m_axi_gmem_in_WLAST),
    .WID(m_axi_gmem_in_WID),
    .WUSER(m_axi_gmem_in_WUSER),
    .ARVALID(m_axi_gmem_in_ARVALID),
    .ARREADY(m_axi_gmem_in_ARREADY),
    .ARADDR(m_axi_gmem_in_ARADDR),
    .ARID(m_axi_gmem_in_ARID),
    .ARLEN(m_axi_gmem_in_ARLEN),
    .ARSIZE(m_axi_gmem_in_ARSIZE),
    .ARBURST(m_axi_gmem_in_ARBURST),
    .ARLOCK(m_axi_gmem_in_ARLOCK),
    .ARCACHE(m_axi_gmem_in_ARCACHE),
    .ARPROT(m_axi_gmem_in_ARPROT),
    .ARQOS(m_axi_gmem_in_ARQOS),
    .ARREGION(m_axi_gmem_in_ARREGION),
    .ARUSER(m_axi_gmem_in_ARUSER),
    .RVALID(m_axi_gmem_in_RVALID),
    .RREADY(m_axi_gmem_in_RREADY),
    .RDATA(m_axi_gmem_in_RDATA),
    .RLAST(m_axi_gmem_in_RLAST),
    .RID(m_axi_gmem_in_RID),
    .RUSER(m_axi_gmem_in_RUSER),
    .RRESP(m_axi_gmem_in_RRESP),
    .BVALID(m_axi_gmem_in_BVALID),
    .BREADY(m_axi_gmem_in_BREADY),
    .BRESP(m_axi_gmem_in_BRESP),
    .BID(m_axi_gmem_in_BID),
    .BUSER(m_axi_gmem_in_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(load_rgb_U0_m_axi_gmem_in_ARVALID),
    .I_CH0_ARREADY(gmem_in_ARREADY),
    .I_CH0_ARADDR(load_rgb_U0_m_axi_gmem_in_ARADDR),
    .I_CH0_ARLEN(load_rgb_U0_m_axi_gmem_in_ARLEN),
    .I_CH0_RVALID(gmem_in_RVALID),
    .I_CH0_RREADY(load_rgb_U0_m_axi_gmem_in_RREADY),
    .I_CH0_RDATA(gmem_in_RDATA),
    .I_CH0_RFIFONUM(gmem_in_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_in_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_in_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem_in_BVALID),
    .I_CH0_BREADY(1'b0)
);

rgb2gray_top_gmem_out_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 73 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_OUT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_OUT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_OUT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_OUT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_OUT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_OUT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_OUT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_OUT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_OUT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_OUT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_OUT_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_out_m_axi_U(
    .AWVALID(m_axi_gmem_out_AWVALID),
    .AWREADY(m_axi_gmem_out_AWREADY),
    .AWADDR(m_axi_gmem_out_AWADDR),
    .AWID(m_axi_gmem_out_AWID),
    .AWLEN(m_axi_gmem_out_AWLEN),
    .AWSIZE(m_axi_gmem_out_AWSIZE),
    .AWBURST(m_axi_gmem_out_AWBURST),
    .AWLOCK(m_axi_gmem_out_AWLOCK),
    .AWCACHE(m_axi_gmem_out_AWCACHE),
    .AWPROT(m_axi_gmem_out_AWPROT),
    .AWQOS(m_axi_gmem_out_AWQOS),
    .AWREGION(m_axi_gmem_out_AWREGION),
    .AWUSER(m_axi_gmem_out_AWUSER),
    .WVALID(m_axi_gmem_out_WVALID),
    .WREADY(m_axi_gmem_out_WREADY),
    .WDATA(m_axi_gmem_out_WDATA),
    .WSTRB(m_axi_gmem_out_WSTRB),
    .WLAST(m_axi_gmem_out_WLAST),
    .WID(m_axi_gmem_out_WID),
    .WUSER(m_axi_gmem_out_WUSER),
    .ARVALID(m_axi_gmem_out_ARVALID),
    .ARREADY(m_axi_gmem_out_ARREADY),
    .ARADDR(m_axi_gmem_out_ARADDR),
    .ARID(m_axi_gmem_out_ARID),
    .ARLEN(m_axi_gmem_out_ARLEN),
    .ARSIZE(m_axi_gmem_out_ARSIZE),
    .ARBURST(m_axi_gmem_out_ARBURST),
    .ARLOCK(m_axi_gmem_out_ARLOCK),
    .ARCACHE(m_axi_gmem_out_ARCACHE),
    .ARPROT(m_axi_gmem_out_ARPROT),
    .ARQOS(m_axi_gmem_out_ARQOS),
    .ARREGION(m_axi_gmem_out_ARREGION),
    .ARUSER(m_axi_gmem_out_ARUSER),
    .RVALID(m_axi_gmem_out_RVALID),
    .RREADY(m_axi_gmem_out_RREADY),
    .RDATA(m_axi_gmem_out_RDATA),
    .RLAST(m_axi_gmem_out_RLAST),
    .RID(m_axi_gmem_out_RID),
    .RUSER(m_axi_gmem_out_RUSER),
    .RRESP(m_axi_gmem_out_RRESP),
    .BVALID(m_axi_gmem_out_BVALID),
    .BREADY(m_axi_gmem_out_BREADY),
    .BRESP(m_axi_gmem_out_BRESP),
    .BID(m_axi_gmem_out_BID),
    .BUSER(m_axi_gmem_out_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem_out_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem_out_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem_out_RDATA),
    .I_CH0_RFIFONUM(gmem_out_RFIFONUM),
    .I_CH0_AWVALID(store_gray_U0_m_axi_gmem_out_AWVALID),
    .I_CH0_AWREADY(gmem_out_AWREADY),
    .I_CH0_AWADDR(store_gray_U0_m_axi_gmem_out_AWADDR),
    .I_CH0_AWLEN(store_gray_U0_m_axi_gmem_out_AWLEN),
    .I_CH0_WVALID(store_gray_U0_m_axi_gmem_out_WVALID),
    .I_CH0_WREADY(gmem_out_WREADY),
    .I_CH0_WDATA(store_gray_U0_m_axi_gmem_out_WDATA),
    .I_CH0_WSTRB(store_gray_U0_m_axi_gmem_out_WSTRB),
    .I_CH0_BVALID(gmem_out_BVALID),
    .I_CH0_BREADY(store_gray_U0_m_axi_gmem_out_BREADY)
);

rgb2gray_top_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_store_gray_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .m_axi_out(m_axi_out),
    .m_axi_out_c_din(entry_proc_U0_m_axi_out_c_din),
    .m_axi_out_c_num_data_valid(m_axi_out_c_num_data_valid),
    .m_axi_out_c_fifo_cap(m_axi_out_c_fifo_cap),
    .m_axi_out_c_full_n(m_axi_out_c_full_n),
    .m_axi_out_c_write(entry_proc_U0_m_axi_out_c_write),
    .addr_out(addr_out),
    .addr_out_c_din(entry_proc_U0_addr_out_c_din),
    .addr_out_c_num_data_valid(addr_out_c_num_data_valid),
    .addr_out_c_fifo_cap(addr_out_c_fifo_cap),
    .addr_out_c_full_n(addr_out_c_full_n),
    .addr_out_c_write(entry_proc_U0_addr_out_c_write)
);

rgb2gray_top_load_rgb load_rgb_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(load_rgb_U0_ap_start),
    .start_full_n(start_for_process_gray_U0_full_n),
    .ap_done(load_rgb_U0_ap_done),
    .ap_continue(load_rgb_U0_ap_continue),
    .ap_idle(load_rgb_U0_ap_idle),
    .ap_ready(load_rgb_U0_ap_ready),
    .m_axi_gmem_in_AWVALID(load_rgb_U0_m_axi_gmem_in_AWVALID),
    .m_axi_gmem_in_AWREADY(1'b0),
    .m_axi_gmem_in_AWADDR(load_rgb_U0_m_axi_gmem_in_AWADDR),
    .m_axi_gmem_in_AWID(load_rgb_U0_m_axi_gmem_in_AWID),
    .m_axi_gmem_in_AWLEN(load_rgb_U0_m_axi_gmem_in_AWLEN),
    .m_axi_gmem_in_AWSIZE(load_rgb_U0_m_axi_gmem_in_AWSIZE),
    .m_axi_gmem_in_AWBURST(load_rgb_U0_m_axi_gmem_in_AWBURST),
    .m_axi_gmem_in_AWLOCK(load_rgb_U0_m_axi_gmem_in_AWLOCK),
    .m_axi_gmem_in_AWCACHE(load_rgb_U0_m_axi_gmem_in_AWCACHE),
    .m_axi_gmem_in_AWPROT(load_rgb_U0_m_axi_gmem_in_AWPROT),
    .m_axi_gmem_in_AWQOS(load_rgb_U0_m_axi_gmem_in_AWQOS),
    .m_axi_gmem_in_AWREGION(load_rgb_U0_m_axi_gmem_in_AWREGION),
    .m_axi_gmem_in_AWUSER(load_rgb_U0_m_axi_gmem_in_AWUSER),
    .m_axi_gmem_in_WVALID(load_rgb_U0_m_axi_gmem_in_WVALID),
    .m_axi_gmem_in_WREADY(1'b0),
    .m_axi_gmem_in_WDATA(load_rgb_U0_m_axi_gmem_in_WDATA),
    .m_axi_gmem_in_WSTRB(load_rgb_U0_m_axi_gmem_in_WSTRB),
    .m_axi_gmem_in_WLAST(load_rgb_U0_m_axi_gmem_in_WLAST),
    .m_axi_gmem_in_WID(load_rgb_U0_m_axi_gmem_in_WID),
    .m_axi_gmem_in_WUSER(load_rgb_U0_m_axi_gmem_in_WUSER),
    .m_axi_gmem_in_ARVALID(load_rgb_U0_m_axi_gmem_in_ARVALID),
    .m_axi_gmem_in_ARREADY(gmem_in_ARREADY),
    .m_axi_gmem_in_ARADDR(load_rgb_U0_m_axi_gmem_in_ARADDR),
    .m_axi_gmem_in_ARID(load_rgb_U0_m_axi_gmem_in_ARID),
    .m_axi_gmem_in_ARLEN(load_rgb_U0_m_axi_gmem_in_ARLEN),
    .m_axi_gmem_in_ARSIZE(load_rgb_U0_m_axi_gmem_in_ARSIZE),
    .m_axi_gmem_in_ARBURST(load_rgb_U0_m_axi_gmem_in_ARBURST),
    .m_axi_gmem_in_ARLOCK(load_rgb_U0_m_axi_gmem_in_ARLOCK),
    .m_axi_gmem_in_ARCACHE(load_rgb_U0_m_axi_gmem_in_ARCACHE),
    .m_axi_gmem_in_ARPROT(load_rgb_U0_m_axi_gmem_in_ARPROT),
    .m_axi_gmem_in_ARQOS(load_rgb_U0_m_axi_gmem_in_ARQOS),
    .m_axi_gmem_in_ARREGION(load_rgb_U0_m_axi_gmem_in_ARREGION),
    .m_axi_gmem_in_ARUSER(load_rgb_U0_m_axi_gmem_in_ARUSER),
    .m_axi_gmem_in_RVALID(gmem_in_RVALID),
    .m_axi_gmem_in_RREADY(load_rgb_U0_m_axi_gmem_in_RREADY),
    .m_axi_gmem_in_RDATA(gmem_in_RDATA),
    .m_axi_gmem_in_RLAST(gmem_in_RLAST),
    .m_axi_gmem_in_RID(gmem_in_RID),
    .m_axi_gmem_in_RFIFONUM(gmem_in_RFIFONUM),
    .m_axi_gmem_in_RUSER(gmem_in_RUSER),
    .m_axi_gmem_in_RRESP(gmem_in_RRESP),
    .m_axi_gmem_in_BVALID(1'b0),
    .m_axi_gmem_in_BREADY(load_rgb_U0_m_axi_gmem_in_BREADY),
    .m_axi_gmem_in_BRESP(2'd0),
    .m_axi_gmem_in_BID(1'd0),
    .m_axi_gmem_in_BUSER(1'd0),
    .stream_rgb_din(load_rgb_U0_stream_rgb_din),
    .stream_rgb_num_data_valid(stream_rgb_num_data_valid),
    .stream_rgb_fifo_cap(stream_rgb_fifo_cap),
    .stream_rgb_full_n(stream_rgb_full_n),
    .stream_rgb_write(load_rgb_U0_stream_rgb_write),
    .start_out(load_rgb_U0_start_out),
    .start_write(load_rgb_U0_start_write),
    .m_axi_in(m_axi_in),
    .addr_in(addr_in),
    .num_pixels(num_pixels),
    .num_pixels_c1_din(load_rgb_U0_num_pixels_c1_din),
    .num_pixels_c1_num_data_valid(num_pixels_c1_num_data_valid),
    .num_pixels_c1_fifo_cap(num_pixels_c1_fifo_cap),
    .num_pixels_c1_full_n(num_pixels_c1_full_n),
    .num_pixels_c1_write(load_rgb_U0_num_pixels_c1_write)
);

rgb2gray_top_process_gray process_gray_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(process_gray_U0_ap_start),
    .ap_done(process_gray_U0_ap_done),
    .ap_continue(process_gray_U0_ap_continue),
    .ap_idle(process_gray_U0_ap_idle),
    .ap_ready(process_gray_U0_ap_ready),
    .stream_rgb_dout(stream_rgb_dout),
    .stream_rgb_num_data_valid(stream_rgb_num_data_valid),
    .stream_rgb_fifo_cap(stream_rgb_fifo_cap),
    .stream_rgb_empty_n(stream_rgb_empty_n),
    .stream_rgb_read(process_gray_U0_stream_rgb_read),
    .stream_gray_din(process_gray_U0_stream_gray_din),
    .stream_gray_num_data_valid(stream_gray_num_data_valid),
    .stream_gray_fifo_cap(stream_gray_fifo_cap),
    .stream_gray_full_n(stream_gray_full_n),
    .stream_gray_write(process_gray_U0_stream_gray_write),
    .num_pixels_dout(num_pixels_c1_dout),
    .num_pixels_num_data_valid(num_pixels_c1_num_data_valid),
    .num_pixels_fifo_cap(num_pixels_c1_fifo_cap),
    .num_pixels_empty_n(num_pixels_c1_empty_n),
    .num_pixels_read(process_gray_U0_num_pixels_read),
    .num_pixels_c_din(process_gray_U0_num_pixels_c_din),
    .num_pixels_c_num_data_valid(num_pixels_c_num_data_valid),
    .num_pixels_c_fifo_cap(num_pixels_c_fifo_cap),
    .num_pixels_c_full_n(num_pixels_c_full_n),
    .num_pixels_c_write(process_gray_U0_num_pixels_c_write)
);

rgb2gray_top_store_gray store_gray_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(store_gray_U0_ap_start),
    .ap_done(store_gray_U0_ap_done),
    .ap_continue(store_gray_U0_ap_continue),
    .ap_idle(store_gray_U0_ap_idle),
    .ap_ready(store_gray_U0_ap_ready),
    .num_pixels_dout(num_pixels_c_dout),
    .num_pixels_num_data_valid(num_pixels_c_num_data_valid),
    .num_pixels_fifo_cap(num_pixels_c_fifo_cap),
    .num_pixels_empty_n(num_pixels_c_empty_n),
    .num_pixels_read(store_gray_U0_num_pixels_read),
    .addr_out_dout(addr_out_c_dout),
    .addr_out_num_data_valid(addr_out_c_num_data_valid),
    .addr_out_fifo_cap(addr_out_c_fifo_cap),
    .addr_out_empty_n(addr_out_c_empty_n),
    .addr_out_read(store_gray_U0_addr_out_read),
    .m_axi_out_dout(m_axi_out_c_dout),
    .m_axi_out_num_data_valid(m_axi_out_c_num_data_valid),
    .m_axi_out_fifo_cap(m_axi_out_c_fifo_cap),
    .m_axi_out_empty_n(m_axi_out_c_empty_n),
    .m_axi_out_read(store_gray_U0_m_axi_out_read),
    .m_axi_gmem_out_AWVALID(store_gray_U0_m_axi_gmem_out_AWVALID),
    .m_axi_gmem_out_AWREADY(gmem_out_AWREADY),
    .m_axi_gmem_out_AWADDR(store_gray_U0_m_axi_gmem_out_AWADDR),
    .m_axi_gmem_out_AWID(store_gray_U0_m_axi_gmem_out_AWID),
    .m_axi_gmem_out_AWLEN(store_gray_U0_m_axi_gmem_out_AWLEN),
    .m_axi_gmem_out_AWSIZE(store_gray_U0_m_axi_gmem_out_AWSIZE),
    .m_axi_gmem_out_AWBURST(store_gray_U0_m_axi_gmem_out_AWBURST),
    .m_axi_gmem_out_AWLOCK(store_gray_U0_m_axi_gmem_out_AWLOCK),
    .m_axi_gmem_out_AWCACHE(store_gray_U0_m_axi_gmem_out_AWCACHE),
    .m_axi_gmem_out_AWPROT(store_gray_U0_m_axi_gmem_out_AWPROT),
    .m_axi_gmem_out_AWQOS(store_gray_U0_m_axi_gmem_out_AWQOS),
    .m_axi_gmem_out_AWREGION(store_gray_U0_m_axi_gmem_out_AWREGION),
    .m_axi_gmem_out_AWUSER(store_gray_U0_m_axi_gmem_out_AWUSER),
    .m_axi_gmem_out_WVALID(store_gray_U0_m_axi_gmem_out_WVALID),
    .m_axi_gmem_out_WREADY(gmem_out_WREADY),
    .m_axi_gmem_out_WDATA(store_gray_U0_m_axi_gmem_out_WDATA),
    .m_axi_gmem_out_WSTRB(store_gray_U0_m_axi_gmem_out_WSTRB),
    .m_axi_gmem_out_WLAST(store_gray_U0_m_axi_gmem_out_WLAST),
    .m_axi_gmem_out_WID(store_gray_U0_m_axi_gmem_out_WID),
    .m_axi_gmem_out_WUSER(store_gray_U0_m_axi_gmem_out_WUSER),
    .m_axi_gmem_out_ARVALID(store_gray_U0_m_axi_gmem_out_ARVALID),
    .m_axi_gmem_out_ARREADY(1'b0),
    .m_axi_gmem_out_ARADDR(store_gray_U0_m_axi_gmem_out_ARADDR),
    .m_axi_gmem_out_ARID(store_gray_U0_m_axi_gmem_out_ARID),
    .m_axi_gmem_out_ARLEN(store_gray_U0_m_axi_gmem_out_ARLEN),
    .m_axi_gmem_out_ARSIZE(store_gray_U0_m_axi_gmem_out_ARSIZE),
    .m_axi_gmem_out_ARBURST(store_gray_U0_m_axi_gmem_out_ARBURST),
    .m_axi_gmem_out_ARLOCK(store_gray_U0_m_axi_gmem_out_ARLOCK),
    .m_axi_gmem_out_ARCACHE(store_gray_U0_m_axi_gmem_out_ARCACHE),
    .m_axi_gmem_out_ARPROT(store_gray_U0_m_axi_gmem_out_ARPROT),
    .m_axi_gmem_out_ARQOS(store_gray_U0_m_axi_gmem_out_ARQOS),
    .m_axi_gmem_out_ARREGION(store_gray_U0_m_axi_gmem_out_ARREGION),
    .m_axi_gmem_out_ARUSER(store_gray_U0_m_axi_gmem_out_ARUSER),
    .m_axi_gmem_out_RVALID(1'b0),
    .m_axi_gmem_out_RREADY(store_gray_U0_m_axi_gmem_out_RREADY),
    .m_axi_gmem_out_RDATA(32'd0),
    .m_axi_gmem_out_RLAST(1'b0),
    .m_axi_gmem_out_RID(1'd0),
    .m_axi_gmem_out_RFIFONUM(9'd0),
    .m_axi_gmem_out_RUSER(1'd0),
    .m_axi_gmem_out_RRESP(2'd0),
    .m_axi_gmem_out_BVALID(gmem_out_BVALID),
    .m_axi_gmem_out_BREADY(store_gray_U0_m_axi_gmem_out_BREADY),
    .m_axi_gmem_out_BRESP(gmem_out_BRESP),
    .m_axi_gmem_out_BID(gmem_out_BID),
    .m_axi_gmem_out_BUSER(gmem_out_BUSER),
    .stream_gray_dout(stream_gray_dout),
    .stream_gray_num_data_valid(stream_gray_num_data_valid),
    .stream_gray_fifo_cap(stream_gray_fifo_cap),
    .stream_gray_empty_n(stream_gray_empty_n),
    .stream_gray_read(store_gray_U0_stream_gray_read)
);

rgb2gray_top_fifo_w64_d4_S m_axi_out_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_m_axi_out_c_din),
    .if_full_n(m_axi_out_c_full_n),
    .if_write(entry_proc_U0_m_axi_out_c_write),
    .if_dout(m_axi_out_c_dout),
    .if_num_data_valid(m_axi_out_c_num_data_valid),
    .if_fifo_cap(m_axi_out_c_fifo_cap),
    .if_empty_n(m_axi_out_c_empty_n),
    .if_read(store_gray_U0_m_axi_out_read)
);

rgb2gray_top_fifo_w32_d4_S addr_out_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_addr_out_c_din),
    .if_full_n(addr_out_c_full_n),
    .if_write(entry_proc_U0_addr_out_c_write),
    .if_dout(addr_out_c_dout),
    .if_num_data_valid(addr_out_c_num_data_valid),
    .if_fifo_cap(addr_out_c_fifo_cap),
    .if_empty_n(addr_out_c_empty_n),
    .if_read(store_gray_U0_addr_out_read)
);

rgb2gray_top_fifo_w24_d16_S stream_rgb_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_rgb_U0_stream_rgb_din),
    .if_full_n(stream_rgb_full_n),
    .if_write(load_rgb_U0_stream_rgb_write),
    .if_dout(stream_rgb_dout),
    .if_num_data_valid(stream_rgb_num_data_valid),
    .if_fifo_cap(stream_rgb_fifo_cap),
    .if_empty_n(stream_rgb_empty_n),
    .if_read(process_gray_U0_stream_rgb_read)
);

rgb2gray_top_fifo_w32_d2_S num_pixels_c1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_rgb_U0_num_pixels_c1_din),
    .if_full_n(num_pixels_c1_full_n),
    .if_write(load_rgb_U0_num_pixels_c1_write),
    .if_dout(num_pixels_c1_dout),
    .if_num_data_valid(num_pixels_c1_num_data_valid),
    .if_fifo_cap(num_pixels_c1_fifo_cap),
    .if_empty_n(num_pixels_c1_empty_n),
    .if_read(process_gray_U0_num_pixels_read)
);

rgb2gray_top_fifo_w8_d16_S stream_gray_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(process_gray_U0_stream_gray_din),
    .if_full_n(stream_gray_full_n),
    .if_write(process_gray_U0_stream_gray_write),
    .if_dout(stream_gray_dout),
    .if_num_data_valid(stream_gray_num_data_valid),
    .if_fifo_cap(stream_gray_fifo_cap),
    .if_empty_n(stream_gray_empty_n),
    .if_read(store_gray_U0_stream_gray_read)
);

rgb2gray_top_fifo_w32_d2_S num_pixels_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(process_gray_U0_num_pixels_c_din),
    .if_full_n(num_pixels_c_full_n),
    .if_write(process_gray_U0_num_pixels_c_write),
    .if_dout(num_pixels_c_dout),
    .if_num_data_valid(num_pixels_c_num_data_valid),
    .if_fifo_cap(num_pixels_c_fifo_cap),
    .if_empty_n(num_pixels_c_empty_n),
    .if_read(store_gray_U0_num_pixels_read)
);

rgb2gray_top_start_for_store_gray_U0 start_for_store_gray_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_store_gray_U0_din),
    .if_full_n(start_for_store_gray_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_store_gray_U0_dout),
    .if_empty_n(start_for_store_gray_U0_empty_n),
    .if_read(store_gray_U0_ap_ready)
);

rgb2gray_top_start_for_process_gray_U0 start_for_process_gray_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_process_gray_U0_din),
    .if_full_n(start_for_process_gray_U0_full_n),
    .if_write(load_rgb_U0_start_write),
    .if_dout(start_for_process_gray_U0_dout),
    .if_empty_n(start_for_process_gray_U0_empty_n),
    .if_read(process_gray_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_load_rgb_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_load_rgb_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_load_rgb_U0_ap_ready <= ap_sync_load_rgb_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign ap_done = store_gray_U0_ap_done;

assign ap_idle = (store_gray_U0_ap_idle & process_gray_U0_ap_idle & load_rgb_U0_ap_idle & entry_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_load_rgb_U0_ap_ready = (load_rgb_U0_ap_ready | ap_sync_reg_load_rgb_U0_ap_ready);

assign ap_sync_ready = (ap_sync_load_rgb_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign gmem_in_RID = 1'd0;

assign gmem_in_RLAST = 1'b0;

assign gmem_in_RRESP = 2'd0;

assign gmem_in_RUSER = 1'd0;

assign gmem_out_BID = 1'd0;

assign gmem_out_BRESP = 2'd0;

assign gmem_out_BUSER = 1'd0;

assign load_rgb_U0_ap_continue = 1'b1;

assign load_rgb_U0_ap_start = ((ap_sync_reg_load_rgb_U0_ap_ready ^ 1'b1) & ap_start);

assign process_gray_U0_ap_continue = 1'b1;

assign process_gray_U0_ap_start = start_for_process_gray_U0_empty_n;

assign start_for_process_gray_U0_din = 1'b1;

assign start_for_store_gray_U0_din = 1'b1;

assign store_gray_U0_ap_continue = ap_continue;

assign store_gray_U0_ap_start = start_for_store_gray_U0_empty_n;

endmodule //rgb2gray_top
