// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module rgb2gray_top_process_gray (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_rgb_dout,
        stream_rgb_num_data_valid,
        stream_rgb_fifo_cap,
        stream_rgb_empty_n,
        stream_rgb_read,
        stream_gray_din,
        stream_gray_num_data_valid,
        stream_gray_fifo_cap,
        stream_gray_full_n,
        stream_gray_write,
        num_pixels_dout,
        num_pixels_num_data_valid,
        num_pixels_fifo_cap,
        num_pixels_empty_n,
        num_pixels_read,
        num_pixels_c_din,
        num_pixels_c_num_data_valid,
        num_pixels_c_fifo_cap,
        num_pixels_c_full_n,
        num_pixels_c_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] stream_rgb_dout;
input  [4:0] stream_rgb_num_data_valid;
input  [4:0] stream_rgb_fifo_cap;
input   stream_rgb_empty_n;
output   stream_rgb_read;
output  [7:0] stream_gray_din;
input  [4:0] stream_gray_num_data_valid;
input  [4:0] stream_gray_fifo_cap;
input   stream_gray_full_n;
output   stream_gray_write;
input  [31:0] num_pixels_dout;
input  [2:0] num_pixels_num_data_valid;
input  [2:0] num_pixels_fifo_cap;
input   num_pixels_empty_n;
output   num_pixels_read;
output  [31:0] num_pixels_c_din;
input  [2:0] num_pixels_c_num_data_valid;
input  [2:0] num_pixels_c_fifo_cap;
input   num_pixels_c_full_n;
output   num_pixels_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_rgb_read;
reg stream_gray_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    num_pixels_blk_n;
reg    num_pixels_c_blk_n;
reg   [31:0] num_pixels_read_reg_65;
reg    ap_block_state1;
wire    grp_process_gray_Pipeline_process_loop_fu_50_ap_start;
wire    grp_process_gray_Pipeline_process_loop_fu_50_ap_done;
wire    grp_process_gray_Pipeline_process_loop_fu_50_ap_idle;
wire    grp_process_gray_Pipeline_process_loop_fu_50_ap_ready;
wire    grp_process_gray_Pipeline_process_loop_fu_50_stream_rgb_read;
wire   [7:0] grp_process_gray_Pipeline_process_loop_fu_50_stream_gray_din;
wire    grp_process_gray_Pipeline_process_loop_fu_50_stream_gray_write;
reg    grp_process_gray_Pipeline_process_loop_fu_50_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    num_pixels_read_local;
reg    num_pixels_c_write_local;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_process_gray_Pipeline_process_loop_fu_50_ap_start_reg = 1'b0;
end

rgb2gray_top_process_gray_Pipeline_process_loop grp_process_gray_Pipeline_process_loop_fu_50(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_process_gray_Pipeline_process_loop_fu_50_ap_start),
    .ap_done(grp_process_gray_Pipeline_process_loop_fu_50_ap_done),
    .ap_idle(grp_process_gray_Pipeline_process_loop_fu_50_ap_idle),
    .ap_ready(grp_process_gray_Pipeline_process_loop_fu_50_ap_ready),
    .stream_rgb_dout(stream_rgb_dout),
    .stream_rgb_num_data_valid(5'd0),
    .stream_rgb_fifo_cap(5'd0),
    .stream_rgb_empty_n(stream_rgb_empty_n),
    .stream_rgb_read(grp_process_gray_Pipeline_process_loop_fu_50_stream_rgb_read),
    .stream_gray_din(grp_process_gray_Pipeline_process_loop_fu_50_stream_gray_din),
    .stream_gray_num_data_valid(5'd0),
    .stream_gray_fifo_cap(5'd0),
    .stream_gray_full_n(stream_gray_full_n),
    .stream_gray_write(grp_process_gray_Pipeline_process_loop_fu_50_stream_gray_write),
    .num_pixels_load(num_pixels_read_reg_65)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_process_gray_Pipeline_process_loop_fu_50_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_process_gray_Pipeline_process_loop_fu_50_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_process_gray_Pipeline_process_loop_fu_50_ap_start_reg <= 1'b1;
        end else if ((grp_process_gray_Pipeline_process_loop_fu_50_ap_ready == 1'b1)) begin
            grp_process_gray_Pipeline_process_loop_fu_50_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_read_reg_65 <= num_pixels_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_process_gray_Pipeline_process_loop_fu_50_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_process_gray_Pipeline_process_loop_fu_50_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_process_gray_Pipeline_process_loop_fu_50_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_blk_n = num_pixels_empty_n;
    end else begin
        num_pixels_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_c_blk_n = num_pixels_c_full_n;
    end else begin
        num_pixels_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_c_write_local = 1'b1;
    end else begin
        num_pixels_c_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_read_local = 1'b1;
    end else begin
        num_pixels_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_gray_write = grp_process_gray_Pipeline_process_loop_fu_50_stream_gray_write;
    end else begin
        stream_gray_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_rgb_read = grp_process_gray_Pipeline_process_loop_fu_50_stream_rgb_read;
    end else begin
        stream_rgb_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_process_gray_Pipeline_process_loop_fu_50_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (num_pixels_c_full_n == 1'b0) | (num_pixels_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_process_gray_Pipeline_process_loop_fu_50_ap_start = grp_process_gray_Pipeline_process_loop_fu_50_ap_start_reg;

assign num_pixels_c_din = num_pixels_dout;

assign num_pixels_c_write = num_pixels_c_write_local;

assign num_pixels_read = num_pixels_read_local;

assign stream_gray_din = grp_process_gray_Pipeline_process_loop_fu_50_stream_gray_din;

endmodule //rgb2gray_top_process_gray
