// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module rgb2gray_top_store_gray (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_gray_dout,
        stream_gray_num_data_valid,
        stream_gray_fifo_cap,
        stream_gray_empty_n,
        stream_gray_read,
        image_out,
        image_out_ap_vld,
        num_pixels_dout,
        num_pixels_num_data_valid,
        num_pixels_fifo_cap,
        num_pixels_empty_n,
        num_pixels_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] stream_gray_dout;
input  [4:0] stream_gray_num_data_valid;
input  [4:0] stream_gray_fifo_cap;
input   stream_gray_empty_n;
output   stream_gray_read;
output  [7:0] image_out;
output   image_out_ap_vld;
input  [31:0] num_pixels_dout;
input  [2:0] num_pixels_num_data_valid;
input  [2:0] num_pixels_fifo_cap;
input   num_pixels_empty_n;
output   num_pixels_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_gray_read;
reg[7:0] image_out;
reg image_out_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    num_pixels_blk_n;
reg   [31:0] num_pixels_1_reg_76;
reg    ap_block_state1;
wire   [0:0] icmp_ln48_fu_61_p2;
reg   [0:0] icmp_ln48_reg_82;
wire    ap_CS_fsm_state2;
wire    grp_store_gray_Pipeline_store_loop_fu_53_ap_start;
wire    grp_store_gray_Pipeline_store_loop_fu_53_ap_done;
wire    grp_store_gray_Pipeline_store_loop_fu_53_ap_idle;
wire    grp_store_gray_Pipeline_store_loop_fu_53_ap_ready;
wire    grp_store_gray_Pipeline_store_loop_fu_53_stream_gray_read;
wire   [7:0] grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out;
wire    grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out_ap_vld;
reg    grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    num_pixels_read_local;
reg   [7:0] image_out_preg;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg = 1'b0;
#0 image_out_preg = 8'd0;
end

rgb2gray_top_store_gray_Pipeline_store_loop grp_store_gray_Pipeline_store_loop_fu_53(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_gray_Pipeline_store_loop_fu_53_ap_start),
    .ap_done(grp_store_gray_Pipeline_store_loop_fu_53_ap_done),
    .ap_idle(grp_store_gray_Pipeline_store_loop_fu_53_ap_idle),
    .ap_ready(grp_store_gray_Pipeline_store_loop_fu_53_ap_ready),
    .stream_gray_dout(stream_gray_dout),
    .stream_gray_num_data_valid(5'd0),
    .stream_gray_fifo_cap(5'd0),
    .stream_gray_empty_n(stream_gray_empty_n),
    .stream_gray_read(grp_store_gray_Pipeline_store_loop_fu_53_stream_gray_read),
    .num_pixels_1(num_pixels_1_reg_76),
    .p_phi_out(grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out),
    .p_phi_out_ap_vld(grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg <= 1'b1;
        end else if ((grp_store_gray_Pipeline_store_loop_fu_53_ap_ready == 1'b1)) begin
            grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        image_out_preg <= 8'd0;
    end else begin
        if (((icmp_ln48_reg_82 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            image_out_preg <= grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln48_reg_82 <= icmp_ln48_fu_61_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_1_reg_76 <= num_pixels_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_store_gray_Pipeline_store_loop_fu_53_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln48_reg_82 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        image_out = grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out;
    end else begin
        image_out = image_out_preg;
    end
end

always @ (*) begin
    if (((icmp_ln48_reg_82 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        image_out_ap_vld = 1'b1;
    end else begin
        image_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_blk_n = num_pixels_empty_n;
    end else begin
        num_pixels_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_read_local = 1'b1;
    end else begin
        num_pixels_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_gray_read = grp_store_gray_Pipeline_store_loop_fu_53_stream_gray_read;
    end else begin
        stream_gray_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_store_gray_Pipeline_store_loop_fu_53_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (num_pixels_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_store_gray_Pipeline_store_loop_fu_53_ap_start = grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg;

assign icmp_ln48_fu_61_p2 = ((num_pixels_1_reg_76 == 32'd0) ? 1'b1 : 1'b0);

assign num_pixels_read = num_pixels_read_local;

endmodule //rgb2gray_top_store_gray
