-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rgb2gray_top is
port (
    image_in : IN STD_LOGIC_VECTOR (7 downto 0);
    image_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    num_pixels : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    image_out_ap_vld : OUT STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of rgb2gray_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "rgb2gray_top_rgb2gray_top,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.920000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=671,HLS_SYN_LUT=932,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal load_rgb_U0_ap_start : STD_LOGIC;
    signal load_rgb_U0_ap_done : STD_LOGIC;
    signal load_rgb_U0_ap_continue : STD_LOGIC;
    signal load_rgb_U0_ap_idle : STD_LOGIC;
    signal load_rgb_U0_ap_ready : STD_LOGIC;
    signal load_rgb_U0_start_out : STD_LOGIC;
    signal load_rgb_U0_start_write : STD_LOGIC;
    signal load_rgb_U0_stream_rgb_din : STD_LOGIC_VECTOR (23 downto 0);
    signal load_rgb_U0_stream_rgb_write : STD_LOGIC;
    signal load_rgb_U0_num_pixels_c1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal load_rgb_U0_num_pixels_c1_write : STD_LOGIC;
    signal process_gray_U0_ap_start : STD_LOGIC;
    signal process_gray_U0_ap_done : STD_LOGIC;
    signal process_gray_U0_ap_continue : STD_LOGIC;
    signal process_gray_U0_ap_idle : STD_LOGIC;
    signal process_gray_U0_ap_ready : STD_LOGIC;
    signal process_gray_U0_start_out : STD_LOGIC;
    signal process_gray_U0_start_write : STD_LOGIC;
    signal process_gray_U0_stream_rgb_read : STD_LOGIC;
    signal process_gray_U0_stream_gray_din : STD_LOGIC_VECTOR (7 downto 0);
    signal process_gray_U0_stream_gray_write : STD_LOGIC;
    signal process_gray_U0_num_pixels_read : STD_LOGIC;
    signal process_gray_U0_num_pixels_c_din : STD_LOGIC_VECTOR (31 downto 0);
    signal process_gray_U0_num_pixels_c_write : STD_LOGIC;
    signal store_gray_U0_ap_start : STD_LOGIC;
    signal store_gray_U0_ap_done : STD_LOGIC;
    signal store_gray_U0_ap_continue : STD_LOGIC;
    signal store_gray_U0_ap_idle : STD_LOGIC;
    signal store_gray_U0_ap_ready : STD_LOGIC;
    signal store_gray_U0_stream_gray_read : STD_LOGIC;
    signal store_gray_U0_image_out : STD_LOGIC_VECTOR (7 downto 0);
    signal store_gray_U0_image_out_ap_vld : STD_LOGIC;
    signal store_gray_U0_num_pixels_read : STD_LOGIC;
    signal stream_rgb_full_n : STD_LOGIC;
    signal stream_rgb_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal stream_rgb_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_rgb_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_rgb_empty_n : STD_LOGIC;
    signal num_pixels_c1_full_n : STD_LOGIC;
    signal num_pixels_c1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal num_pixels_c1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c1_empty_n : STD_LOGIC;
    signal stream_gray_full_n : STD_LOGIC;
    signal stream_gray_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal stream_gray_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_gray_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal stream_gray_empty_n : STD_LOGIC;
    signal num_pixels_c_full_n : STD_LOGIC;
    signal num_pixels_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal num_pixels_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c_empty_n : STD_LOGIC;
    signal start_for_process_gray_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_process_gray_U0_full_n : STD_LOGIC;
    signal start_for_process_gray_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_process_gray_U0_empty_n : STD_LOGIC;
    signal start_for_store_gray_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_store_gray_U0_full_n : STD_LOGIC;
    signal start_for_store_gray_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_store_gray_U0_empty_n : STD_LOGIC;

    component rgb2gray_top_load_rgb IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        image_in : IN STD_LOGIC_VECTOR (7 downto 0);
        stream_rgb_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_rgb_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_rgb_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_rgb_full_n : IN STD_LOGIC;
        stream_rgb_write : OUT STD_LOGIC;
        num_pixels : IN STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_c1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_c1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c1_full_n : IN STD_LOGIC;
        num_pixels_c1_write : OUT STD_LOGIC );
    end component;


    component rgb2gray_top_process_gray IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        stream_rgb_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        stream_rgb_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_rgb_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_rgb_empty_n : IN STD_LOGIC;
        stream_rgb_read : OUT STD_LOGIC;
        stream_gray_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        stream_gray_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_gray_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_gray_full_n : IN STD_LOGIC;
        stream_gray_write : OUT STD_LOGIC;
        num_pixels_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_empty_n : IN STD_LOGIC;
        num_pixels_read : OUT STD_LOGIC;
        num_pixels_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c_full_n : IN STD_LOGIC;
        num_pixels_c_write : OUT STD_LOGIC );
    end component;


    component rgb2gray_top_store_gray IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_gray_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        stream_gray_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_gray_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_gray_empty_n : IN STD_LOGIC;
        stream_gray_read : OUT STD_LOGIC;
        image_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        image_out_ap_vld : OUT STD_LOGIC;
        num_pixels_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_empty_n : IN STD_LOGIC;
        num_pixels_read : OUT STD_LOGIC );
    end component;


    component rgb2gray_top_fifo_w24_d16_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (23 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (23 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rgb2gray_top_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rgb2gray_top_fifo_w8_d16_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rgb2gray_top_start_for_process_gray_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rgb2gray_top_start_for_store_gray_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    load_rgb_U0 : component rgb2gray_top_load_rgb
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => load_rgb_U0_ap_start,
        start_full_n => start_for_process_gray_U0_full_n,
        ap_done => load_rgb_U0_ap_done,
        ap_continue => load_rgb_U0_ap_continue,
        ap_idle => load_rgb_U0_ap_idle,
        ap_ready => load_rgb_U0_ap_ready,
        start_out => load_rgb_U0_start_out,
        start_write => load_rgb_U0_start_write,
        image_in => image_in,
        stream_rgb_din => load_rgb_U0_stream_rgb_din,
        stream_rgb_num_data_valid => stream_rgb_num_data_valid,
        stream_rgb_fifo_cap => stream_rgb_fifo_cap,
        stream_rgb_full_n => stream_rgb_full_n,
        stream_rgb_write => load_rgb_U0_stream_rgb_write,
        num_pixels => num_pixels,
        num_pixels_c1_din => load_rgb_U0_num_pixels_c1_din,
        num_pixels_c1_num_data_valid => num_pixels_c1_num_data_valid,
        num_pixels_c1_fifo_cap => num_pixels_c1_fifo_cap,
        num_pixels_c1_full_n => num_pixels_c1_full_n,
        num_pixels_c1_write => load_rgb_U0_num_pixels_c1_write);

    process_gray_U0 : component rgb2gray_top_process_gray
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => process_gray_U0_ap_start,
        start_full_n => start_for_store_gray_U0_full_n,
        ap_done => process_gray_U0_ap_done,
        ap_continue => process_gray_U0_ap_continue,
        ap_idle => process_gray_U0_ap_idle,
        ap_ready => process_gray_U0_ap_ready,
        start_out => process_gray_U0_start_out,
        start_write => process_gray_U0_start_write,
        stream_rgb_dout => stream_rgb_dout,
        stream_rgb_num_data_valid => stream_rgb_num_data_valid,
        stream_rgb_fifo_cap => stream_rgb_fifo_cap,
        stream_rgb_empty_n => stream_rgb_empty_n,
        stream_rgb_read => process_gray_U0_stream_rgb_read,
        stream_gray_din => process_gray_U0_stream_gray_din,
        stream_gray_num_data_valid => stream_gray_num_data_valid,
        stream_gray_fifo_cap => stream_gray_fifo_cap,
        stream_gray_full_n => stream_gray_full_n,
        stream_gray_write => process_gray_U0_stream_gray_write,
        num_pixels_dout => num_pixels_c1_dout,
        num_pixels_num_data_valid => num_pixels_c1_num_data_valid,
        num_pixels_fifo_cap => num_pixels_c1_fifo_cap,
        num_pixels_empty_n => num_pixels_c1_empty_n,
        num_pixels_read => process_gray_U0_num_pixels_read,
        num_pixels_c_din => process_gray_U0_num_pixels_c_din,
        num_pixels_c_num_data_valid => num_pixels_c_num_data_valid,
        num_pixels_c_fifo_cap => num_pixels_c_fifo_cap,
        num_pixels_c_full_n => num_pixels_c_full_n,
        num_pixels_c_write => process_gray_U0_num_pixels_c_write);

    store_gray_U0 : component rgb2gray_top_store_gray
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => store_gray_U0_ap_start,
        ap_done => store_gray_U0_ap_done,
        ap_continue => store_gray_U0_ap_continue,
        ap_idle => store_gray_U0_ap_idle,
        ap_ready => store_gray_U0_ap_ready,
        stream_gray_dout => stream_gray_dout,
        stream_gray_num_data_valid => stream_gray_num_data_valid,
        stream_gray_fifo_cap => stream_gray_fifo_cap,
        stream_gray_empty_n => stream_gray_empty_n,
        stream_gray_read => store_gray_U0_stream_gray_read,
        image_out => store_gray_U0_image_out,
        image_out_ap_vld => store_gray_U0_image_out_ap_vld,
        num_pixels_dout => num_pixels_c_dout,
        num_pixels_num_data_valid => num_pixels_c_num_data_valid,
        num_pixels_fifo_cap => num_pixels_c_fifo_cap,
        num_pixels_empty_n => num_pixels_c_empty_n,
        num_pixels_read => store_gray_U0_num_pixels_read);

    stream_rgb_U : component rgb2gray_top_fifo_w24_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => load_rgb_U0_stream_rgb_din,
        if_full_n => stream_rgb_full_n,
        if_write => load_rgb_U0_stream_rgb_write,
        if_dout => stream_rgb_dout,
        if_num_data_valid => stream_rgb_num_data_valid,
        if_fifo_cap => stream_rgb_fifo_cap,
        if_empty_n => stream_rgb_empty_n,
        if_read => process_gray_U0_stream_rgb_read);

    num_pixels_c1_U : component rgb2gray_top_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => load_rgb_U0_num_pixels_c1_din,
        if_full_n => num_pixels_c1_full_n,
        if_write => load_rgb_U0_num_pixels_c1_write,
        if_dout => num_pixels_c1_dout,
        if_num_data_valid => num_pixels_c1_num_data_valid,
        if_fifo_cap => num_pixels_c1_fifo_cap,
        if_empty_n => num_pixels_c1_empty_n,
        if_read => process_gray_U0_num_pixels_read);

    stream_gray_U : component rgb2gray_top_fifo_w8_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => process_gray_U0_stream_gray_din,
        if_full_n => stream_gray_full_n,
        if_write => process_gray_U0_stream_gray_write,
        if_dout => stream_gray_dout,
        if_num_data_valid => stream_gray_num_data_valid,
        if_fifo_cap => stream_gray_fifo_cap,
        if_empty_n => stream_gray_empty_n,
        if_read => store_gray_U0_stream_gray_read);

    num_pixels_c_U : component rgb2gray_top_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => process_gray_U0_num_pixels_c_din,
        if_full_n => num_pixels_c_full_n,
        if_write => process_gray_U0_num_pixels_c_write,
        if_dout => num_pixels_c_dout,
        if_num_data_valid => num_pixels_c_num_data_valid,
        if_fifo_cap => num_pixels_c_fifo_cap,
        if_empty_n => num_pixels_c_empty_n,
        if_read => store_gray_U0_num_pixels_read);

    start_for_process_gray_U0_U : component rgb2gray_top_start_for_process_gray_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_process_gray_U0_din,
        if_full_n => start_for_process_gray_U0_full_n,
        if_write => load_rgb_U0_start_write,
        if_dout => start_for_process_gray_U0_dout,
        if_empty_n => start_for_process_gray_U0_empty_n,
        if_read => process_gray_U0_ap_ready);

    start_for_store_gray_U0_U : component rgb2gray_top_start_for_store_gray_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_store_gray_U0_din,
        if_full_n => start_for_store_gray_U0_full_n,
        if_write => process_gray_U0_start_write,
        if_dout => start_for_store_gray_U0_dout,
        if_empty_n => start_for_store_gray_U0_empty_n,
        if_read => store_gray_U0_ap_ready);




    ap_done <= store_gray_U0_ap_done;
    ap_idle <= (store_gray_U0_ap_idle and process_gray_U0_ap_idle and load_rgb_U0_ap_idle);
    ap_ready <= load_rgb_U0_ap_ready;
    image_out <= store_gray_U0_image_out;
    image_out_ap_vld <= store_gray_U0_image_out_ap_vld;
    load_rgb_U0_ap_continue <= ap_const_logic_1;
    load_rgb_U0_ap_start <= ap_start;
    process_gray_U0_ap_continue <= ap_const_logic_1;
    process_gray_U0_ap_start <= start_for_process_gray_U0_empty_n;
    start_for_process_gray_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_store_gray_U0_din <= (0=>ap_const_logic_1, others=>'-');
    store_gray_U0_ap_continue <= ap_const_logic_1;
    store_gray_U0_ap_start <= start_for_store_gray_U0_empty_n;
end behav;
