// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rgb2gray_top_rgb2gray_top,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.920000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=671,HLS_SYN_LUT=932,HLS_VERSION=2024_1}" *)

module rgb2gray_top (
        image_in,
        image_out,
        num_pixels,
        ap_clk,
        ap_rst,
        ap_start,
        image_out_ap_vld,
        ap_done,
        ap_ready,
        ap_idle
);


input  [7:0] image_in;
output  [7:0] image_out;
input  [31:0] num_pixels;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   image_out_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    load_rgb_U0_ap_start;
wire    load_rgb_U0_ap_done;
wire    load_rgb_U0_ap_continue;
wire    load_rgb_U0_ap_idle;
wire    load_rgb_U0_ap_ready;
wire    load_rgb_U0_start_out;
wire    load_rgb_U0_start_write;
wire   [23:0] load_rgb_U0_stream_rgb_din;
wire    load_rgb_U0_stream_rgb_write;
wire   [31:0] load_rgb_U0_num_pixels_c1_din;
wire    load_rgb_U0_num_pixels_c1_write;
wire    process_gray_U0_ap_start;
wire    process_gray_U0_ap_done;
wire    process_gray_U0_ap_continue;
wire    process_gray_U0_ap_idle;
wire    process_gray_U0_ap_ready;
wire    process_gray_U0_start_out;
wire    process_gray_U0_start_write;
wire    process_gray_U0_stream_rgb_read;
wire   [7:0] process_gray_U0_stream_gray_din;
wire    process_gray_U0_stream_gray_write;
wire    process_gray_U0_num_pixels_read;
wire   [31:0] process_gray_U0_num_pixels_c_din;
wire    process_gray_U0_num_pixels_c_write;
wire    store_gray_U0_ap_start;
wire    store_gray_U0_ap_done;
wire    store_gray_U0_ap_continue;
wire    store_gray_U0_ap_idle;
wire    store_gray_U0_ap_ready;
wire    store_gray_U0_stream_gray_read;
wire   [7:0] store_gray_U0_image_out;
wire    store_gray_U0_image_out_ap_vld;
wire    store_gray_U0_num_pixels_read;
wire    stream_rgb_full_n;
wire   [23:0] stream_rgb_dout;
wire   [4:0] stream_rgb_num_data_valid;
wire   [4:0] stream_rgb_fifo_cap;
wire    stream_rgb_empty_n;
wire    num_pixels_c1_full_n;
wire   [31:0] num_pixels_c1_dout;
wire   [2:0] num_pixels_c1_num_data_valid;
wire   [2:0] num_pixels_c1_fifo_cap;
wire    num_pixels_c1_empty_n;
wire    stream_gray_full_n;
wire   [7:0] stream_gray_dout;
wire   [4:0] stream_gray_num_data_valid;
wire   [4:0] stream_gray_fifo_cap;
wire    stream_gray_empty_n;
wire    num_pixels_c_full_n;
wire   [31:0] num_pixels_c_dout;
wire   [2:0] num_pixels_c_num_data_valid;
wire   [2:0] num_pixels_c_fifo_cap;
wire    num_pixels_c_empty_n;
wire   [0:0] start_for_process_gray_U0_din;
wire    start_for_process_gray_U0_full_n;
wire   [0:0] start_for_process_gray_U0_dout;
wire    start_for_process_gray_U0_empty_n;
wire   [0:0] start_for_store_gray_U0_din;
wire    start_for_store_gray_U0_full_n;
wire   [0:0] start_for_store_gray_U0_dout;
wire    start_for_store_gray_U0_empty_n;

rgb2gray_top_load_rgb load_rgb_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_rgb_U0_ap_start),
    .start_full_n(start_for_process_gray_U0_full_n),
    .ap_done(load_rgb_U0_ap_done),
    .ap_continue(load_rgb_U0_ap_continue),
    .ap_idle(load_rgb_U0_ap_idle),
    .ap_ready(load_rgb_U0_ap_ready),
    .start_out(load_rgb_U0_start_out),
    .start_write(load_rgb_U0_start_write),
    .image_in(image_in),
    .stream_rgb_din(load_rgb_U0_stream_rgb_din),
    .stream_rgb_num_data_valid(stream_rgb_num_data_valid),
    .stream_rgb_fifo_cap(stream_rgb_fifo_cap),
    .stream_rgb_full_n(stream_rgb_full_n),
    .stream_rgb_write(load_rgb_U0_stream_rgb_write),
    .num_pixels(num_pixels),
    .num_pixels_c1_din(load_rgb_U0_num_pixels_c1_din),
    .num_pixels_c1_num_data_valid(num_pixels_c1_num_data_valid),
    .num_pixels_c1_fifo_cap(num_pixels_c1_fifo_cap),
    .num_pixels_c1_full_n(num_pixels_c1_full_n),
    .num_pixels_c1_write(load_rgb_U0_num_pixels_c1_write)
);

rgb2gray_top_process_gray process_gray_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(process_gray_U0_ap_start),
    .start_full_n(start_for_store_gray_U0_full_n),
    .ap_done(process_gray_U0_ap_done),
    .ap_continue(process_gray_U0_ap_continue),
    .ap_idle(process_gray_U0_ap_idle),
    .ap_ready(process_gray_U0_ap_ready),
    .start_out(process_gray_U0_start_out),
    .start_write(process_gray_U0_start_write),
    .stream_rgb_dout(stream_rgb_dout),
    .stream_rgb_num_data_valid(stream_rgb_num_data_valid),
    .stream_rgb_fifo_cap(stream_rgb_fifo_cap),
    .stream_rgb_empty_n(stream_rgb_empty_n),
    .stream_rgb_read(process_gray_U0_stream_rgb_read),
    .stream_gray_din(process_gray_U0_stream_gray_din),
    .stream_gray_num_data_valid(stream_gray_num_data_valid),
    .stream_gray_fifo_cap(stream_gray_fifo_cap),
    .stream_gray_full_n(stream_gray_full_n),
    .stream_gray_write(process_gray_U0_stream_gray_write),
    .num_pixels_dout(num_pixels_c1_dout),
    .num_pixels_num_data_valid(num_pixels_c1_num_data_valid),
    .num_pixels_fifo_cap(num_pixels_c1_fifo_cap),
    .num_pixels_empty_n(num_pixels_c1_empty_n),
    .num_pixels_read(process_gray_U0_num_pixels_read),
    .num_pixels_c_din(process_gray_U0_num_pixels_c_din),
    .num_pixels_c_num_data_valid(num_pixels_c_num_data_valid),
    .num_pixels_c_fifo_cap(num_pixels_c_fifo_cap),
    .num_pixels_c_full_n(num_pixels_c_full_n),
    .num_pixels_c_write(process_gray_U0_num_pixels_c_write)
);

rgb2gray_top_store_gray store_gray_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(store_gray_U0_ap_start),
    .ap_done(store_gray_U0_ap_done),
    .ap_continue(store_gray_U0_ap_continue),
    .ap_idle(store_gray_U0_ap_idle),
    .ap_ready(store_gray_U0_ap_ready),
    .stream_gray_dout(stream_gray_dout),
    .stream_gray_num_data_valid(stream_gray_num_data_valid),
    .stream_gray_fifo_cap(stream_gray_fifo_cap),
    .stream_gray_empty_n(stream_gray_empty_n),
    .stream_gray_read(store_gray_U0_stream_gray_read),
    .image_out(store_gray_U0_image_out),
    .image_out_ap_vld(store_gray_U0_image_out_ap_vld),
    .num_pixels_dout(num_pixels_c_dout),
    .num_pixels_num_data_valid(num_pixels_c_num_data_valid),
    .num_pixels_fifo_cap(num_pixels_c_fifo_cap),
    .num_pixels_empty_n(num_pixels_c_empty_n),
    .num_pixels_read(store_gray_U0_num_pixels_read)
);

rgb2gray_top_fifo_w24_d16_S stream_rgb_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_rgb_U0_stream_rgb_din),
    .if_full_n(stream_rgb_full_n),
    .if_write(load_rgb_U0_stream_rgb_write),
    .if_dout(stream_rgb_dout),
    .if_num_data_valid(stream_rgb_num_data_valid),
    .if_fifo_cap(stream_rgb_fifo_cap),
    .if_empty_n(stream_rgb_empty_n),
    .if_read(process_gray_U0_stream_rgb_read)
);

rgb2gray_top_fifo_w32_d2_S num_pixels_c1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_rgb_U0_num_pixels_c1_din),
    .if_full_n(num_pixels_c1_full_n),
    .if_write(load_rgb_U0_num_pixels_c1_write),
    .if_dout(num_pixels_c1_dout),
    .if_num_data_valid(num_pixels_c1_num_data_valid),
    .if_fifo_cap(num_pixels_c1_fifo_cap),
    .if_empty_n(num_pixels_c1_empty_n),
    .if_read(process_gray_U0_num_pixels_read)
);

rgb2gray_top_fifo_w8_d16_S stream_gray_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(process_gray_U0_stream_gray_din),
    .if_full_n(stream_gray_full_n),
    .if_write(process_gray_U0_stream_gray_write),
    .if_dout(stream_gray_dout),
    .if_num_data_valid(stream_gray_num_data_valid),
    .if_fifo_cap(stream_gray_fifo_cap),
    .if_empty_n(stream_gray_empty_n),
    .if_read(store_gray_U0_stream_gray_read)
);

rgb2gray_top_fifo_w32_d2_S num_pixels_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(process_gray_U0_num_pixels_c_din),
    .if_full_n(num_pixels_c_full_n),
    .if_write(process_gray_U0_num_pixels_c_write),
    .if_dout(num_pixels_c_dout),
    .if_num_data_valid(num_pixels_c_num_data_valid),
    .if_fifo_cap(num_pixels_c_fifo_cap),
    .if_empty_n(num_pixels_c_empty_n),
    .if_read(store_gray_U0_num_pixels_read)
);

rgb2gray_top_start_for_process_gray_U0 start_for_process_gray_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_process_gray_U0_din),
    .if_full_n(start_for_process_gray_U0_full_n),
    .if_write(load_rgb_U0_start_write),
    .if_dout(start_for_process_gray_U0_dout),
    .if_empty_n(start_for_process_gray_U0_empty_n),
    .if_read(process_gray_U0_ap_ready)
);

rgb2gray_top_start_for_store_gray_U0 start_for_store_gray_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_store_gray_U0_din),
    .if_full_n(start_for_store_gray_U0_full_n),
    .if_write(process_gray_U0_start_write),
    .if_dout(start_for_store_gray_U0_dout),
    .if_empty_n(start_for_store_gray_U0_empty_n),
    .if_read(store_gray_U0_ap_ready)
);

assign ap_done = store_gray_U0_ap_done;

assign ap_idle = (store_gray_U0_ap_idle & process_gray_U0_ap_idle & load_rgb_U0_ap_idle);

assign ap_ready = load_rgb_U0_ap_ready;

assign image_out = store_gray_U0_image_out;

assign image_out_ap_vld = store_gray_U0_image_out_ap_vld;

assign load_rgb_U0_ap_continue = 1'b1;

assign load_rgb_U0_ap_start = ap_start;

assign process_gray_U0_ap_continue = 1'b1;

assign process_gray_U0_ap_start = start_for_process_gray_U0_empty_n;

assign start_for_process_gray_U0_din = 1'b1;

assign start_for_store_gray_U0_din = 1'b1;

assign store_gray_U0_ap_continue = 1'b1;

assign store_gray_U0_ap_start = start_for_store_gray_U0_empty_n;

endmodule //rgb2gray_top
