// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module rgb2gray_top_load_rgb (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        image_in,
        stream_rgb_din,
        stream_rgb_num_data_valid,
        stream_rgb_fifo_cap,
        stream_rgb_full_n,
        stream_rgb_write,
        num_pixels,
        num_pixels_c1_din,
        num_pixels_c1_num_data_valid,
        num_pixels_c1_fifo_cap,
        num_pixels_c1_full_n,
        num_pixels_c1_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] image_in;
output  [23:0] stream_rgb_din;
input  [4:0] stream_rgb_num_data_valid;
input  [4:0] stream_rgb_fifo_cap;
input   stream_rgb_full_n;
output   stream_rgb_write;
input  [31:0] num_pixels;
output  [31:0] num_pixels_c1_din;
input  [2:0] num_pixels_c1_num_data_valid;
input  [2:0] num_pixels_c1_fifo_cap;
input   num_pixels_c1_full_n;
output   num_pixels_c1_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg stream_rgb_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    num_pixels_c1_blk_n;
reg    ap_block_state1;
wire   [23:0] or_ln20_3_fu_68_p4;
reg   [23:0] or_ln20_3_reg_88;
wire    ap_CS_fsm_state2;
wire    grp_load_rgb_Pipeline_load_loop_fu_60_ap_start;
wire    grp_load_rgb_Pipeline_load_loop_fu_60_ap_done;
wire    grp_load_rgb_Pipeline_load_loop_fu_60_ap_idle;
wire    grp_load_rgb_Pipeline_load_loop_fu_60_ap_ready;
wire   [23:0] grp_load_rgb_Pipeline_load_loop_fu_60_stream_rgb_din;
wire    grp_load_rgb_Pipeline_load_loop_fu_60_stream_rgb_write;
reg    grp_load_rgb_Pipeline_load_loop_fu_60_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    num_pixels_c1_write_local;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_load_rgb_Pipeline_load_loop_fu_60_ap_start_reg = 1'b0;
end

rgb2gray_top_load_rgb_Pipeline_load_loop grp_load_rgb_Pipeline_load_loop_fu_60(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_rgb_Pipeline_load_loop_fu_60_ap_start),
    .ap_done(grp_load_rgb_Pipeline_load_loop_fu_60_ap_done),
    .ap_idle(grp_load_rgb_Pipeline_load_loop_fu_60_ap_idle),
    .ap_ready(grp_load_rgb_Pipeline_load_loop_fu_60_ap_ready),
    .stream_rgb_din(grp_load_rgb_Pipeline_load_loop_fu_60_stream_rgb_din),
    .stream_rgb_num_data_valid(5'd0),
    .stream_rgb_fifo_cap(5'd0),
    .stream_rgb_full_n(stream_rgb_full_n),
    .stream_rgb_write(grp_load_rgb_Pipeline_load_loop_fu_60_stream_rgb_write),
    .num_pixels(num_pixels),
    .or_ln20_3(or_ln20_3_reg_88)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_load_rgb_Pipeline_load_loop_fu_60_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_rgb_Pipeline_load_loop_fu_60_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_load_rgb_Pipeline_load_loop_fu_60_ap_start_reg <= 1'b1;
        end else if ((grp_load_rgb_Pipeline_load_loop_fu_60_ap_ready == 1'b1)) begin
            grp_load_rgb_Pipeline_load_loop_fu_60_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        or_ln20_3_reg_88 <= or_ln20_3_fu_68_p4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_load_rgb_Pipeline_load_loop_fu_60_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_load_rgb_Pipeline_load_loop_fu_60_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_load_rgb_Pipeline_load_loop_fu_60_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_c1_blk_n = num_pixels_c1_full_n;
    end else begin
        num_pixels_c1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_c1_write_local = 1'b1;
    end else begin
        num_pixels_c1_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_rgb_write = grp_load_rgb_Pipeline_load_loop_fu_60_stream_rgb_write;
    end else begin
        stream_rgb_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_load_rgb_Pipeline_load_loop_fu_60_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (num_pixels_c1_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign grp_load_rgb_Pipeline_load_loop_fu_60_ap_start = grp_load_rgb_Pipeline_load_loop_fu_60_ap_start_reg;

assign num_pixels_c1_din = num_pixels;

assign num_pixels_c1_write = num_pixels_c1_write_local;

assign or_ln20_3_fu_68_p4 = {{{image_in}, {image_in}}, {image_in}};

assign start_out = real_start;

assign stream_rgb_din = grp_load_rgb_Pipeline_load_loop_fu_60_stream_rgb_din;

endmodule //rgb2gray_top_load_rgb
