#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOLUTION_DIR="${1:-${SOLUTION_DIR:-$SCRIPT_DIR/wht_hls_work/wht_hls/solution_kv260}}"
XML_PATH="$SOLUTION_DIR/syn/report/wht_lossless_core_csynth.xml"
OUT_MD="$SCRIPT_DIR/metrics_prelim.md"

if [[ ! -f "$XML_PATH" ]]; then
  echo "ERROR: Could not find csynth XML at: $XML_PATH" >&2
  exit 1
fi

get_xml_tag() {
  local tag="$1"
  local value
  value="$(tr -d '\r\n' < "$XML_PATH" | sed -n "s:.*<$tag>\\([^<]*\\)</$tag>.*:\\1:p" | head -n1)"
  if [[ -z "$value" ]]; then
    echo "N/A"
  else
    echo "$value"
  fi
}

clock_est_ns="$(get_xml_tag EstimatedClockPeriod)"
latency_best="$(get_xml_tag Best-caseLatency)"
latency_worst="$(get_xml_tag Worst-caseLatency)"
pipe_depth="$(get_xml_tag PipelineDepth)"
ii_min="$(get_xml_tag Interval-min)"
ii_max="$(get_xml_tag Interval-max)"
lut="$(get_xml_tag LUT)"
ff="$(get_xml_tag FF)"
dsp="$(get_xml_tag DSP)"
bram="$(get_xml_tag BRAM_18K)"

fmax_mhz="N/A"
if [[ "$clock_est_ns" != "N/A" ]]; then
  fmax_mhz="$(awk -v p="$clock_est_ns" 'BEGIN{if (p+0 > 0) printf "%.2f", 1000.0/p; else print "N/A"}')"
fi

throughput_blocks="N/A"
throughput_samples="N/A"
if [[ "$fmax_mhz" != "N/A" && "$ii_min" != "N/A" ]]; then
  throughput_blocks="$(awk -v f="$fmax_mhz" -v ii="$ii_min" 'BEGIN{if (ii+0 > 0) printf "%.2f", f/ii; else print "N/A"}')"
  throughput_samples="$(awk -v t="$throughput_blocks" 'BEGIN{if (t == "N/A") print "N/A"; else printf "%.2f", t*8.0}')"
fi

cat > "$OUT_MD" <<EOF
# W2 Preliminary Hardware Metrics

Source: csynth report generated by Vitis HLS.

| Metric | Value |
|---|---|
| Estimated clock (ns) | $clock_est_ns |
| Estimated fmax (MHz) | $fmax_mhz |
| Latency best (cycles) | $latency_best |
| Latency worst (cycles) | $latency_worst |
| Pipeline depth (cycles) | $pipe_depth |
| Initiation interval min (cycles) | $ii_min |
| Initiation interval max (cycles) | $ii_max |
| LUT | $lut |
| FF | $ff |
| DSP | $dsp |
| BRAM_18K | $bram |

## Throughput estimate

Assuming steady state with II=1:

- Block throughput: $throughput_blocks Mblocks/s
- Sample throughput (N=8): $throughput_samples Msamples/s
EOF

echo "Metrics written to: $OUT_MD"
echo "Estimated fmax (MHz): $fmax_mhz"
echo "DSP usage: $dsp"
