param(
    [string]$SolutionDir = "$PSScriptRoot\wht_hls_work\wht_hls\solution_kv260"
)

$ErrorActionPreference = "Stop"

$xmlPath = Join-Path $SolutionDir "syn\report\wht_lossless_core_csynth.xml"
$outMd = Join-Path $PSScriptRoot "metrics_prelim.md"

if (-not (Test-Path $xmlPath)) {
    Write-Error "Could not find csynth XML at: $xmlPath"
    exit 1
}

[xml]$doc = Get-Content $xmlPath

function Get-NodeValue {
    param(
        [xml]$XmlDoc,
        [string]$XPath,
        [string]$Default = "N/A"
    )

    $node = $XmlDoc.SelectSingleNode($XPath)
    if ($null -eq $node -or [string]::IsNullOrWhiteSpace($node.InnerText)) {
        return $Default
    }

    return $node.InnerText.Trim()
}

$clockEstNs = Get-NodeValue -XmlDoc $doc -XPath "//PerformanceEstimates/SummaryOfTimingAnalysis/EstimatedClockPeriod"

$latencyBest = Get-NodeValue -XmlDoc $doc -XPath "//PerformanceEstimates/SummaryOfOverallLatency/Best-caseLatency"
$latencyWorst = Get-NodeValue -XmlDoc $doc -XPath "//PerformanceEstimates/SummaryOfOverallLatency/Worst-caseLatency"
$pipeDepth = Get-NodeValue -XmlDoc $doc -XPath "//PerformanceEstimates/SummaryOfOverallLatency/PipelineDepth"
$iiMin = Get-NodeValue -XmlDoc $doc -XPath "//PerformanceEstimates/SummaryOfOverallLatency/Interval-min"
$iiMax = Get-NodeValue -XmlDoc $doc -XPath "//PerformanceEstimates/SummaryOfOverallLatency/Interval-max"

$lut = Get-NodeValue -XmlDoc $doc -XPath "//AreaEstimates/Resources/LUT"
$ff = Get-NodeValue -XmlDoc $doc -XPath "//AreaEstimates/Resources/FF"
$dsp = Get-NodeValue -XmlDoc $doc -XPath "//AreaEstimates/Resources/DSP"
$bram = Get-NodeValue -XmlDoc $doc -XPath "//AreaEstimates/Resources/BRAM_18K"

$fmaxMHz = "N/A"
if ($clockEstNs -ne "N/A") {
    try {
        $period = [double]::Parse($clockEstNs, [System.Globalization.CultureInfo]::InvariantCulture)
        if ($period -gt 0.0) {
            $fmaxMHz = [math]::Round(1000.0 / $period, 2)
        }
    }
    catch {
        $fmaxMHz = "N/A"
    }
}

$throughputBlocks = "N/A"
$throughputSamples = "N/A"
if ($fmaxMHz -ne "N/A") {
    $ii = 0.0
    if ([double]::TryParse($iiMin, [ref]$ii) -and $ii -gt 0.0) {
        $throughputBlocks = [math]::Round($fmaxMHz / $ii, 2)
        $throughputSamples = [math]::Round(($fmaxMHz / $ii) * 8.0, 2)
    }
}

$lines = @(
    "# Preliminary Hardware Metrics",
    "",
    "Source: csynth report generated by Vitis HLS.",
    "",
    "| Metric | Value |",
    "|---|---|",
    "| Estimated clock (ns) | $clockEstNs |",
    "| Estimated fmax (MHz) | $fmaxMHz |",
    "| Latency best (cycles) | $latencyBest |",
    "| Latency worst (cycles) | $latencyWorst |",
    "| Pipeline depth (cycles) | $pipeDepth |",
    "| Initiation interval min (cycles) | $iiMin |",
    "| Initiation interval max (cycles) | $iiMax |",
    "| LUT | $lut |",
    "| FF | $ff |",
    "| DSP | $dsp |",
    "| BRAM_18K | $bram |",
    "",
    "## Throughput estimate",
    "",
    "Assuming steady state with II=1:",
    "",
    "- Block throughput: $throughputBlocks Mblocks/s",
    "- Sample throughput (N=8): $throughputSamples Msamples/s"
)

Set-Content -Path $outMd -Value ($lines -join "`r`n") -Encoding ASCII

Write-Host "Metrics written to: $outMd"
Write-Host "Estimated fmax (MHz): $fmaxMHz"
Write-Host "DSP usage: $dsp"
