-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rgb2gray_top_store_gray is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_gray_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_gray_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_gray_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_gray_empty_n : IN STD_LOGIC;
    stream_gray_read : OUT STD_LOGIC;
    image_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    image_out_ap_vld : OUT STD_LOGIC;
    num_pixels_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    num_pixels_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    num_pixels_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    num_pixels_empty_n : IN STD_LOGIC;
    num_pixels_read : OUT STD_LOGIC );
end;


architecture behav of rgb2gray_top_store_gray is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal num_pixels_blk_n : STD_LOGIC;
    signal num_pixels_1_reg_76 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal icmp_ln48_fu_61_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_82 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_store_gray_Pipeline_store_loop_fu_53_ap_start : STD_LOGIC;
    signal grp_store_gray_Pipeline_store_loop_fu_53_ap_done : STD_LOGIC;
    signal grp_store_gray_Pipeline_store_loop_fu_53_ap_idle : STD_LOGIC;
    signal grp_store_gray_Pipeline_store_loop_fu_53_ap_ready : STD_LOGIC;
    signal grp_store_gray_Pipeline_store_loop_fu_53_stream_gray_read : STD_LOGIC;
    signal grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out_ap_vld : STD_LOGIC;
    signal grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal num_pixels_read_local : STD_LOGIC;
    signal image_out_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component rgb2gray_top_store_gray_Pipeline_store_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_gray_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        stream_gray_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_gray_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_gray_empty_n : IN STD_LOGIC;
        stream_gray_read : OUT STD_LOGIC;
        num_pixels_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_phi_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_phi_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_store_gray_Pipeline_store_loop_fu_53 : component rgb2gray_top_store_gray_Pipeline_store_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_store_gray_Pipeline_store_loop_fu_53_ap_start,
        ap_done => grp_store_gray_Pipeline_store_loop_fu_53_ap_done,
        ap_idle => grp_store_gray_Pipeline_store_loop_fu_53_ap_idle,
        ap_ready => grp_store_gray_Pipeline_store_loop_fu_53_ap_ready,
        stream_gray_dout => stream_gray_dout,
        stream_gray_num_data_valid => ap_const_lv5_0,
        stream_gray_fifo_cap => ap_const_lv5_0,
        stream_gray_empty_n => stream_gray_empty_n,
        stream_gray_read => grp_store_gray_Pipeline_store_loop_fu_53_stream_gray_read,
        num_pixels_1 => num_pixels_1_reg_76,
        p_phi_out => grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out,
        p_phi_out_ap_vld => grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_store_gray_Pipeline_store_loop_fu_53_ap_ready = ap_const_logic_1)) then 
                    grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    image_out_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                image_out_preg <= ap_const_lv8_0;
            else
                if (((icmp_ln48_reg_82 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    image_out_preg <= grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln48_reg_82 <= icmp_ln48_fu_61_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                num_pixels_1_reg_76 <= num_pixels_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_store_gray_Pipeline_store_loop_fu_53_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_store_gray_Pipeline_store_loop_fu_53_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_store_gray_Pipeline_store_loop_fu_53_ap_done)
    begin
        if ((grp_store_gray_Pipeline_store_loop_fu_53_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, num_pixels_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (num_pixels_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_store_gray_Pipeline_store_loop_fu_53_ap_start <= grp_store_gray_Pipeline_store_loop_fu_53_ap_start_reg;
    icmp_ln48_fu_61_p2 <= "1" when (num_pixels_1_reg_76 = ap_const_lv32_0) else "0";

    image_out_assign_proc : process(icmp_ln48_reg_82, grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out, ap_CS_fsm_state4, image_out_preg)
    begin
        if (((icmp_ln48_reg_82 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            image_out <= grp_store_gray_Pipeline_store_loop_fu_53_p_phi_out;
        else 
            image_out <= image_out_preg;
        end if; 
    end process;


    image_out_ap_vld_assign_proc : process(icmp_ln48_reg_82, ap_CS_fsm_state4)
    begin
        if (((icmp_ln48_reg_82 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            image_out_ap_vld <= ap_const_logic_1;
        else 
            image_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    num_pixels_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_pixels_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_pixels_blk_n <= num_pixels_empty_n;
        else 
            num_pixels_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_pixels_read <= num_pixels_read_local;

    num_pixels_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_pixels_read_local <= ap_const_logic_1;
        else 
            num_pixels_read_local <= ap_const_logic_0;
        end if; 
    end process;


    stream_gray_read_assign_proc : process(grp_store_gray_Pipeline_store_loop_fu_53_stream_gray_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            stream_gray_read <= grp_store_gray_Pipeline_store_loop_fu_53_stream_gray_read;
        else 
            stream_gray_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
